# AUTO-GENERATED — DO NOT EDIT
# Generated by fixture_codegen v0.0.0 at 2026-05-11T00:00:00Z.
from __future__ import annotations

GENERATED_TABLE: dict[str, int] = {
    "alpha": 1,
    "beta": 2,
    "gamma": 3,
}
