import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

/**
 * `ai-eng bootstrap` — scaffold a new project (subcribed-IDE friendly).
 *
 * Phase 0 implementation: creates the minimum local layout. Full stack
 * detection + CONSTITUTION generation lands in Phase 4 (driving adapters).
 */
export const bootstrap = async (_args: string[]): Promise<number> => {
  const cwd = process.cwd();
  const root = join(cwd, ".ai-engineering");
  const dirs = [
    "specs",
    "state",
    "contexts/frameworks",
    "contexts/team",
    "policies",
    "compliance",
  ];
  await mkdir(root, { recursive: true });
  for (const d of dirs) {
    await mkdir(join(root, d), { recursive: true });
  }
  await writeFile(
    join(root, "manifest.toml"),
    [
      "# Project-level ai-engineering manifest (generated by `ai-eng bootstrap`).",
      "# See ai-engineering.toml at the framework root for framework-level config.",
      "",
      'schema_version = "1"',
      "",
      "[project]",
      `name = "${cwd.split("/").pop() ?? "my-project"}"`,
      'profile = "default"   # default | banking | healthcare | fintech | airgapped',
      "",
      "[ides]",
      "# Detected on first run; ai-eng sync-mirrors will materialize them.",
      "detected = []",
      "",
      "[llm]",
      'mode = "piggyback"   # piggyback | byok',
      'privacy_tier = "standard"',
      "",
      "[telemetry]",
      "enabled = true",
      'ndjson = ".ai-engineering/state/framework-events.ndjson'.concat('"'),
      "",
    ].join("\n"),
    "utf8",
  );
  await writeFile(join(root, "state", ".gitkeep"), "", "utf8");
  process.stdout.write(
    `[ai-eng] bootstrap complete. Files written under ${root}\n`,
  );
  return 0;
};
