import { readdir, readFile, mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";

/**
 * `ai-eng sync-mirrors` — regenerate IDE mirrors from `skills/catalog/`.
 *
 * Single Source of Truth: each `skills/catalog/<name>/SKILL.md` gets
 * mirrored to .claude/, .cursor/, .codex/, .gemini/, .github/. Generated
 * files include a `DO NOT EDIT` header and are listed under
 * `linguist-generated=true` in `.gitattributes`.
 *
 * Phase 4 will plug in the IDE-specific adapters (Cursor needs `.mdc`
 * format, Copilot wants AGENTS.md aggregation, etc.). For now this
 * implements the simplest case: literal copy to `.claude/skills/`.
 */
const HEADER =
  "<!-- DO NOT EDIT — generated by `ai-eng sync-mirrors` from skills/catalog/. -->\n\n";

export const syncMirrors = async (_args: string[]): Promise<number> => {
  const cwd = process.cwd();
  const catalog = join(cwd, "skills", "catalog");
  if (!existsSync(catalog)) {
    process.stderr.write(
      "[ai-eng] no skills/catalog/ found — nothing to sync\n",
    );
    return 1;
  }
  const tier1Out = join(cwd, ".claude", "skills");
  await mkdir(tier1Out, { recursive: true });

  const entries = await readdir(catalog, { withFileTypes: true });
  let count = 0;
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const src = join(catalog, entry.name, "SKILL.md");
    if (!existsSync(src)) continue;
    const content = await readFile(src, "utf8");
    const dst = join(tier1Out, entry.name, "SKILL.md");
    await mkdir(join(tier1Out, entry.name), { recursive: true });
    await writeFile(dst, HEADER + content, "utf8");
    count++;
  }
  process.stdout.write(
    `[ai-eng] sync-mirrors: ${count} skill(s) mirrored to .claude/skills/.\n`,
  );
  return 0;
};
