// GENERATED by `ai-eng dev sync` (scripts/sync_mirrors/opencode_target.py::generate_opencode_plugin).
// mirror_family: opencode-plugin
// edit_policy: generated-do-not-edit
// canonical_source: .ai-engineering/scripts/hooks/opencode-hook-bridge.ts
//
// OpenCode 1.18.5 auto-discovers `*.ts` under `.opencode/plugin/`, so this
// file is the whole wiring: it re-exports the canonical bridge's default
// `Plugin`, which runs the ai-engineering guards and blocks on exit 2.

export { default } from "../../.ai-engineering/scripts/hooks/opencode-hook-bridge.ts";
