"""Hook script integrity verification (sha256 manifest check).

CLAUDE.md (line 34) commits to "hash-verified hook scripts". This module
implements that contract: each hook execution can verify its own bytes
against a committed manifest, refusing to run (or warning) on mismatch.

Modes (env: ``AIENG_HOOK_INTEGRITY_MODE``):

* ``enforce`` -- fail-closed. Mismatch raises SystemExit(2) so the IDE
  knows the hook refused. Use in CI / production.
* ``warn`` (default) -- log a ``framework_error`` event but allow the
  hook to run. Suits day-to-day development where hooks change often.
* ``off`` -- skip the check entirely (no audit event).

The manifest path is ``.ai-engineering/state/hooks-manifest.json`` with
shape ``{"hooks": {"<repo-relative-path>": "<sha256-hex>"}, ...}``.
Regenerated by ``scripts/regenerate-hooks-manifest.py`` after any
intentional edit to a hook script.

Sealed contract: stdlib-only (no ``ai_engineering.*`` imports), matches
the rest of ``_lib``.
"""

from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path

_MANIFEST_REL = Path(".ai-engineering") / "state" / "hooks-manifest.json"
_DEFAULT_MODE = "warn"
_VALID_MODES: frozenset[str] = frozenset({"enforce", "warn", "off"})


def _resolve_mode() -> str:
    raw = (os.environ.get("AIENG_HOOK_INTEGRITY_MODE") or "").strip().lower()
    if raw in _VALID_MODES:
        return raw
    return _DEFAULT_MODE


def compute_file_sha256(path: Path) -> str:
    """Return canonical lowercase sha256 hex of ``path`` contents."""
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def load_manifest(project_root: Path) -> dict[str, str]:
    """Return ``{relative_path: sha256}`` mapping; empty dict if absent."""
    manifest_path = project_root / _MANIFEST_REL
    if not manifest_path.exists():
        return {}
    try:
        payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError, ValueError):
        return {}
    hooks = payload.get("hooks") if isinstance(payload, dict) else None
    if not isinstance(hooks, dict):
        return {}
    return {str(k): str(v) for k, v in hooks.items() if isinstance(v, str)}


def verify_hook_integrity(script_path: Path, project_root: Path) -> tuple[bool, str | None]:
    """Verify ``script_path`` matches the committed manifest entry.

    Returns ``(ok, reason)``. ``ok=True`` means the script either matches
    or has no manifest entry (forward-compat for new hooks not yet
    enrolled). ``reason`` is a short human-readable string when ok is
    False, suitable for telemetry summaries.
    """
    manifest = load_manifest(project_root)
    if not manifest:
        return True, None
    try:
        rel = script_path.resolve().relative_to(project_root.resolve())
    except ValueError:
        # Hook lives outside the project; nothing to verify against.
        return True, None
    expected = manifest.get(str(rel))
    if expected is None:
        # New hook not yet enrolled; treat as pass to avoid bricking
        # day-one installs after the manifest landed.
        return True, None
    actual = compute_file_sha256(script_path)
    if actual.lower() == expected.lower():
        return True, None
    return False, f"sha256 mismatch (expected {expected[:12]}…, got {actual[:12]}…)"


def integrity_mode() -> str:
    return _resolve_mode()


def manifest_path(project_root: Path) -> Path:
    return project_root / _MANIFEST_REL


__all__ = [
    "compute_file_sha256",
    "integrity_mode",
    "load_manifest",
    "manifest_path",
    "verify_hook_integrity",
]
