"""Golden snapshot tests for ``ai-eng`` help output (spec-132 D-132-11).

For every public top-level command and every public subcommand discovered in
:func:`ai_engineering.cli_factory.create_app`, this test renders
``<verb> --help`` and asserts the output matches a checked-in snapshot under
``tests/golden/cli/help_snapshots/``.

Snapshots are regenerated by setting the ``AIENG_UPDATE_HELP_SNAPSHOTS=1``
environment variable. The contract is:

* Output is decoded with the system default; ANSI escape sequences are
  stripped so the snapshot is plain text.
* Trailing whitespace and trailing blank lines are normalised so terminal
  width differences do not produce false diffs.
* When a snapshot is missing AND the env var is unset, the test fails and
  prints the regeneration command.
"""

from __future__ import annotations

import os
import re
from collections.abc import Iterator
from pathlib import Path

import pytest
import typer
from typer.testing import CliRunner

from ai_engineering.cli_factory import create_app

SNAPSHOT_DIR = Path(__file__).resolve().parents[2] / "golden" / "cli" / "help_snapshots"
ANSI_RE = re.compile(r"\x1b\[[0-9;]*[A-Za-z]")
TRAILING_WS_RE = re.compile(r"[ \t]+$", re.MULTILINE)


def _walk_public(app: typer.Typer, prefix: tuple[str, ...] = ()) -> Iterator[tuple[str, ...]]:
    """Yield verb paths for every public command (skips hidden + opt-out groups)."""
    opt_out_groups = {"internal", "dev"}
    in_opt_out = any(seg in opt_out_groups for seg in prefix)
    if in_opt_out:
        return
    for cmd in app.registered_commands:
        if cmd.name is None or cmd.hidden:
            continue
        yield (*prefix, cmd.name)
    for group in app.registered_groups:
        if group.name is None or group.typer_instance is None or group.hidden:
            continue
        if group.name in opt_out_groups:
            continue
        yield from _walk_public(group.typer_instance, (*prefix, group.name))


def _normalise(text: str) -> str:
    """Strip ANSI codes, trailing whitespace, and trailing blank lines."""
    text = ANSI_RE.sub("", text)
    text = TRAILING_WS_RE.sub("", text)
    return text.rstrip() + "\n"


def _snapshot_filename(verb_path: tuple[str, ...]) -> str:
    return "_".join(verb_path) + ".txt"


def _render_help(verb_path: tuple[str, ...]) -> str:
    """Render ``<verb> --help`` deterministically.

    Pins ``COLUMNS=80`` and ``TERMINAL_WIDTH=80`` so the Rich panel wrapping
    is reproducible regardless of the operator's actual terminal width.
    """
    app = create_app()
    runner = CliRunner()
    env = {"COLUMNS": "80", "TERMINAL_WIDTH": "80", "NO_COLOR": "1"}
    result = runner.invoke(
        app,
        [*verb_path, "--help"],
        catch_exceptions=False,
        color=False,
        env=env,
    )
    assert result.exit_code == 0, (
        f"`ai-eng {' '.join(verb_path)} --help` exited {result.exit_code}. Output:\n{result.output}"
    )
    return _normalise(result.output)


PUBLIC_VERBS: list[tuple[str, ...]] = list(_walk_public(create_app()))


@pytest.mark.parametrize("verb_path", PUBLIC_VERBS, ids=lambda path: "_".join(path))
def test_help_snapshot_matches(verb_path: tuple[str, ...]) -> None:
    """`<verb> --help` output matches the checked-in golden snapshot."""
    rendered = _render_help(verb_path)
    snapshot_path = SNAPSHOT_DIR / _snapshot_filename(verb_path)

    if os.environ.get("AIENG_UPDATE_HELP_SNAPSHOTS") == "1":
        snapshot_path.parent.mkdir(parents=True, exist_ok=True)
        snapshot_path.write_text(rendered, encoding="utf-8")
        return

    assert snapshot_path.exists(), (
        f"Missing golden snapshot at {snapshot_path}. Regenerate with:\n"
        f"  AIENG_UPDATE_HELP_SNAPSHOTS=1 uv run pytest "
        f"tests/integration/cli/test_help_snapshots.py"
    )
    expected = snapshot_path.read_text(encoding="utf-8")
    assert rendered == expected, (
        f"Help-text drift for `ai-eng {' '.join(verb_path)}`.\n"
        f"Snapshot: {snapshot_path}\n"
        f"Regenerate with AIENG_UPDATE_HELP_SNAPSHOTS=1 if the change is intentional."
    )
