import { writeFile, ensureDir, resolvePath } from "../utils/filesystem.js";
import { logger } from "../utils/logger.js";
import type { Config } from "../utils/config.js";

function generateGitHubActionsCI(config: Config): string {
  const sections: string[] = [
    "# Generated by ai-engineering",
    "",
    "name: CI",
    "",
    "on:",
    "  push:",
    `    branches: [${config.branches.protectedBranches.map((b) => `"${b}"`).join(", ")}]`,
    "  pull_request:",
    `    branches: [${config.branches.protectedBranches.map((b) => `"${b}"`).join(", ")}]`,
    "",
    "permissions:",
    "  contents: read",
    "",
    "jobs:",
    "  quality:",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - uses: actions/checkout@v4",
  ];

  if (config.stacks.includes("typescript-react")) {
    sections.push(
      "      - uses: actions/setup-node@v4",
      "        with:",
      "          node-version: 20",
      "          cache: npm",
      "      - run: npm ci",
      "      - run: npm run lint",
      "      - run: npm run typecheck",
      "      - run: npm test -- --coverage",
    );
  }

  if (config.stacks.includes("python")) {
    sections.push(
      "      - uses: actions/setup-python@v5",
      "        with:",
      '          python-version: "3.12"',
      "      - run: pip install -r requirements.txt",
      "      - run: ruff check .",
      "      - run: pytest --cov --cov-report=xml",
    );
  }

  if (config.stacks.includes("dotnet")) {
    sections.push(
      "      - uses: actions/setup-dotnet@v4",
      "        with:",
      '          dotnet-version: "8.0.x"',
      "      - run: dotnet restore",
      "      - run: dotnet build --no-restore",
      '      - run: dotnet test --no-build --collect:"XPlat Code Coverage"',
    );
  }

  // Security scanning
  sections.push(
    "",
    "  security:",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - uses: actions/checkout@v4",
    "        with:",
    "          fetch-depth: 0",
    "      - uses: gitleaks/gitleaks-action@v2",
    "        env:",
    "          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}",
    "      - uses: semgrep/semgrep-action@v1",
    "        with:",
    "          config: auto",
  );

  if (config.stacks.includes("typescript-react")) {
    sections.push(
      "      - uses: actions/setup-node@v4",
      "        with:",
      "          node-version: 20",
      "          cache: npm",
      "      - run: npm ci",
      "      - run: npm audit --audit-level=high",
    );
  }

  // SonarQube (conditional on sonar-project.properties)
  sections.push(
    "      - name: SonarQube Analysis",
    "        if: hashFiles('sonar-project.properties') != ''",
    "        uses: sonarsource/sonarqube-scan-action@v3",
    "      - name: SonarQube Quality Gate",
    "        if: hashFiles('sonar-project.properties') != ''",
    "        uses: sonarsource/sonarqube-quality-gate-action@v1",
  );

  return sections.join("\n") + "\n";
}

function generateGitHubActionsQualityGate(config: Config): string {
  const sections: string[] = [
    "# Generated by ai-engineering",
    "# Quality gate — blocks merge if checks fail",
    "",
    "name: Quality Gate",
    "",
    "on:",
    "  pull_request:",
    `    branches: [${config.branches.protectedBranches.map((b) => `"${b}"`).join(", ")}]`,
    "",
    "permissions:",
    "  contents: read",
    "  pull-requests: write",
    "",
    "jobs:",
    "  gate:",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - uses: actions/checkout@v4",
  ];

  if (config.stacks.includes("typescript-react")) {
    sections.push(
      "      - uses: actions/setup-node@v4",
      "        with:",
      "          node-version: 20",
      "          cache: npm",
      "      - run: npm ci",
      "      - name: Run all checks",
      "        run: |",
      "          npm run lint",
      "          npm run typecheck",
      "          npm test -- --coverage",
      "          npm audit --audit-level=high",
    );
  }

  sections.push(
    "      - name: Semgrep SAST",
    "        uses: semgrep/semgrep-action@v1",
    "        with:",
    "          config: auto",
    "      - name: Check coverage threshold",
    "        run: |",
    '          echo "Coverage threshold check would run here"',
    '          echo "Minimum: 80% statements, branches, functions, lines"',
    "      - name: SonarQube Quality Gate",
    "        if: hashFiles('sonar-project.properties') != ''",
    "        uses: sonarsource/sonarqube-quality-gate-action@v1",
  );

  return sections.join("\n") + "\n";
}

function generateAzurePipelinesCI(config: Config): string {
  const sections: string[] = [
    "# Generated by ai-engineering",
    "",
    "trigger:",
    "  branches:",
    "    include:",
    ...config.branches.protectedBranches.map((b) => `      - ${b}`),
    "",
    "pr:",
    "  branches:",
    "    include:",
    ...config.branches.protectedBranches.map((b) => `      - ${b}`),
    "",
    "pool:",
    "  vmImage: ubuntu-latest",
    "",
    "stages:",
    "  - stage: Quality",
    "    jobs:",
    "      - job: Build",
    "        steps:",
  ];

  if (config.stacks.includes("typescript-react")) {
    sections.push(
      "          - task: NodeTool@0",
      "            inputs:",
      '              versionSpec: "20.x"',
      "          - script: npm ci",
      "            displayName: Install dependencies",
      "          - script: npm run lint",
      "            displayName: Lint",
      "          - script: npm run typecheck",
      "            displayName: Type check",
      "          - script: npm test -- --coverage",
      "            displayName: Test",
    );
  }

  if (config.stacks.includes("dotnet")) {
    sections.push(
      "          - task: UseDotNet@2",
      "            inputs:",
      "              packageType: sdk",
      '              version: "8.0.x"',
      "          - script: dotnet restore",
      "            displayName: Restore",
      "          - script: dotnet build --no-restore",
      "            displayName: Build",
      "          - script: dotnet test --no-build",
      "            displayName: Test",
    );
  }

  sections.push(
    "",
    "  - stage: Security",
    "    jobs:",
    "      - job: Scan",
    "        steps:",
    "          - checkout: self",
    "            fetchDepth: 0",
    "          - script: |",
    "              curl -sSfL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_linux_x64 -o gitleaks",
    "              chmod +x gitleaks",
    "              ./gitleaks detect --no-banner",
    "            displayName: Gitleaks scan",
    "          - script: |",
    "              pip install semgrep",
    "              semgrep --config=auto --error .",
    "            displayName: Semgrep SAST",
  );

  return sections.join("\n") + "\n";
}

function generateAzurePipelinesQualityGate(config: Config): string {
  return [
    "# Generated by ai-engineering",
    "# Quality gate for pull requests",
    "",
    "trigger: none",
    "",
    "pr:",
    "  branches:",
    "    include:",
    ...config.branches.protectedBranches.map((b) => `      - ${b}`),
    "",
    "pool:",
    "  vmImage: ubuntu-latest",
    "",
    "steps:",
    "  - checkout: self",
    "  - script: |",
    "      pip install semgrep",
    "      semgrep --config=auto --error .",
    "    displayName: Semgrep SAST",
    '  - script: echo "Quality gate checks"',
    "    displayName: Quality Gate",
    "",
  ].join("\n");
}

export function installGates(projectRoot: string, config: Config): void {
  logger.step(4, 4, "Installing CI/CD quality gates...");

  if (config.platform === "github") {
    const workflowsDir = resolvePath(projectRoot, ".github/workflows");
    ensureDir(workflowsDir);

    writeFile(
      resolvePath(workflowsDir, "ci.yml"),
      generateGitHubActionsCI(config),
    );
    writeFile(
      resolvePath(workflowsDir, "quality-gate.yml"),
      generateGitHubActionsQualityGate(config),
    );
    logger.success("Generated GitHub Actions workflows");
  }

  if (config.platform === "azure-devops") {
    writeFile(
      resolvePath(projectRoot, "azure-pipelines.yml"),
      generateAzurePipelinesCI(config),
    );
    writeFile(
      resolvePath(projectRoot, "azure-pipelines-quality-gate.yml"),
      generateAzurePipelinesQualityGate(config),
    );
    logger.success("Generated Azure Pipelines");
  }
}
