"""Markdown adapter for the conformance report.

Implements the ``ReporterPort`` protocol with two surfaces:

* :meth:`MarkdownReporter.render` — terse Markdown table for a single
  rubric report.
* :meth:`MarkdownReporter.render_baseline` — the M1 baseline section
  written to ``docs/conformance-report.md`` (per plan T-G.2).
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

from skill_app.lint_agents import AgentRubricResult, AgentsRubricReport
from skill_app.lint_skills import SkillRubricResult, SkillsRubricReport


class MarkdownReporter:
    """Render rubric reports as Markdown."""

    def render(self, report: object) -> str:
        if isinstance(report, SkillsRubricReport):
            return self._render_skills(report)
        if isinstance(report, AgentsRubricReport):
            return self._render_agents(report)
        raise TypeError(f"unsupported report type: {type(report).__name__}")

    # ------------------------------------------------------------------
    # Baseline (T-G.2) — full Markdown section for docs/conformance-report.md
    # ------------------------------------------------------------------

    def render_baseline(
        self,
        *,
        skills_report: SkillsRubricReport,
        agents_report: AgentsRubricReport,
        elapsed_ms: float,
    ) -> str:
        today = date.today().isoformat()
        skills = skills_report.summary
        agents = agents_report.summary
        lines: list[str] = []
        lines.append(f"## M1 Baseline ({today})")
        lines.append("")
        lines.append(
            "Generated by `python -m skill_lint --baseline` over the live "
            "`.claude/skills/` and `.claude/agents/` surface. Reproduces "
            "brief §2.1 grade vector for the conformance rubric."
        )
        lines.append("")
        lines.append(
            f"- **Skills graded**: {len(skills_report.per_skill)} (brief §2.1 baseline target: 50)"
        )
        lines.append(f"- **Agents graded**: {len(agents_report.per_agent)}")
        lines.append(f"- **Lint wall-time**: {elapsed_ms:.1f} ms (D-127-08 budget: ≤200 ms)")
        lines.append("")
        lines.append("### Grade vector — skills")
        lines.append("")
        lines.append("| Grade | Count | Brief §2.1 target |")
        lines.append("|-------|-------|-------------------|")
        lines.append(f"| A     | {skills.get('A', 0):<5} | 28                |")
        lines.append(f"| B     | {skills.get('B', 0):<5} | 14                |")
        lines.append(f"| C     | {skills.get('C', 0):<5} | 6                 |")
        lines.append(f"| D     | {skills.get('D', 0):<5} | 1                 |")
        lines.append("")
        lines.append("### Grade vector — agents")
        lines.append("")
        lines.append("| Grade | Count |")
        lines.append("|-------|-------|")
        lines.append(f"| A     | {agents.get('A', 0)}     |")
        lines.append(f"| B     | {agents.get('B', 0)}     |")
        lines.append(f"| C     | {agents.get('C', 0)}     |")
        lines.append(f"| D     | {agents.get('D', 0)}     |")
        lines.append("")
        lines.append("### Per-skill grade detail")
        lines.append("")
        lines.append(self._render_skills(skills_report))
        lines.append("")
        lines.append("### Per-agent grade detail")
        lines.append("")
        lines.append(self._render_agents(agents_report))
        lines.append("")
        lines.append(
            "> Universal §2.1 gap: 0/50 skills carry a `## Examples` "
            "block; rule_6 fires on every current skill. M2 closes "
            "this gap (skills excellence pass)."
        )
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Internal renderers
    # ------------------------------------------------------------------

    def _render_skills(self, report: SkillsRubricReport) -> str:
        rows = [
            "| Skill | Grade | Score | Top reasons |",
            "|-------|-------|-------|-------------|",
        ]
        for r in report.per_skill:
            rows.append(_format_row_skill(r))
        return "\n".join(rows)

    def _render_agents(self, report: AgentsRubricReport) -> str:
        rows = [
            "| Agent | Grade | Score | Top reasons |",
            "|-------|-------|-------|-------------|",
        ]
        for r in report.per_agent:
            rows.append(_format_row_agent(r))
        return "\n".join(rows)


def _format_row_skill(r: SkillRubricResult) -> str:
    reasons = "; ".join(rr.reason for rr in r.rule_results if rr.severity != "OK")[:120]
    return f"| `{_path_repr(r.path)}` | {r.grade} | {r.score} | {reasons or '—'} |"


def _format_row_agent(r: AgentRubricResult) -> str:
    reasons = "; ".join(rr.reason for rr in r.rule_results if rr.severity != "OK")[:120]
    return f"| `{_path_repr(r.path)}` | {r.grade} | {r.score} | {reasons or '—'} |"


def _path_repr(path: Path) -> str:
    """Path for display — strip leading repo prefix."""
    s = str(path)
    return s
