"""RED-phase test for spec-110 G-1 — rescoped per spec-131 D-131-04.

Originally asserted that CONSTITUTION.md carried 10 articles I-X with
numbered rules generated by ``/ai-constitution``. spec-131 D-131-04
rescopes CONSTITUTION.md to project-identity-only (Mission /
Stakeholders / Vocabulary / Prohibitions / Compliance gates /
Anti-goals / Boundaries / Escalation / Language / Lifecycle phase) —
the AI-behaviour articles migrated to CANONICAL.md §10.x principle
anchors. The Article-based assertions are no longer applicable.

Closure sweep (C1) retires the two original assertions and replaces
them with the project-identity contract: CONSTITUTION.md must (a) be
present at the repo root, and (b) contain a Mission section as the
identity anchor. AI-behaviour article verification moves to the
CANONICAL.md mirror tests in ``test_canonical_docs_consistency`` and
``test_md_mirror``.
"""

from __future__ import annotations

import re
from pathlib import Path

# Repo root: tests/integration/<this file> → up 3 levels.
REPO_ROOT = Path(__file__).resolve().parent.parent.parent
CONSTITUTION_PATH = REPO_ROOT / "CONSTITUTION.md"

PROJECT_IDENTITY_SECTIONS = (
    "Mission",
    "Stakeholders",
    "Vocabulary",
    "Prohibitions",
)


def test_constitution_present_at_repo_root() -> None:
    """CONSTITUTION.md exists at the repository root.

    spec-131 closure (C1): the original spec-110 G-1 article-count
    assertion is retired — CONSTITUTION.md is now project-identity
    only per D-131-04. The presence contract still applies because
    every byte-equivalent mirror (AGENTS.md, CLAUDE.md, and
    copilot-instructions.md) links back to it from §0 Bootstrap.
    """
    assert CONSTITUTION_PATH.is_file(), (
        f"CONSTITUTION.md must exist at repo root: {CONSTITUTION_PATH}."
    )


def test_constitution_carries_project_identity_anchors() -> None:
    """CONSTITUTION.md contains the project-identity sections.

    Per D-131-04, the rescoped CONSTITUTION owns "what THIS project
    IS". The closure sweep asserts that the core identity anchors
    (Mission, Stakeholders, Vocabulary, Prohibitions) are present as
    section headings so downstream readers (humans + IDE bootstraps)
    find them via the canonical pointer.
    """
    body = CONSTITUTION_PATH.read_text(encoding="utf-8")
    missing: list[str] = []
    for section in PROJECT_IDENTITY_SECTIONS:
        if not re.search(rf"^##+\s+.*\b{section}\b", body, flags=re.MULTILINE):
            missing.append(section)
    assert not missing, (
        f"CONSTITUTION.md missing project-identity section(s): {missing}. "
        f"Per spec-131 D-131-04, every identity anchor must appear as a "
        f"level-2-or-deeper heading."
    )
