// .agents/hooks/ai-eng.ts — generated by ai-eng init (Oh My Pi). In-process module:
// deny = { block }, input rewrite supported, zero spawn.
import { chain } from "./ai-eng-chain.ts";

type ToolCall = { tool: string; input: Record<string, unknown>; sessionID?: string; callID?: string };

export function beforeToolCall(call: ToolCall): { block?: boolean; reason?: string; input?: Record<string, unknown> } {
  const outcome = chain(
    "PreToolUse",
    { tool_name: call.tool, tool_input: call.input, session_id: call.sessionID, tool_use_id: call.callID },
    { surface: "oh-my-pi", dialect: "in-process" },
  );
  if (outcome.action === "deny") return { block: true, reason: `[ai-eng] ${outcome.by}: ${outcome.reason}` };
  if (outcome.action === "rewrite") return { input: { ...call.input, command: outcome.command } };
  return {};
}

export function afterToolCall(call: ToolCall, result: unknown): { block?: boolean; reason?: string } {
  const outcome = chain(
    "PostToolUse",
    { tool_name: call.tool, tool_input: call.input, tool_response: result, session_id: call.sessionID, tool_use_id: call.callID },
    { surface: "oh-my-pi", dialect: "in-process" },
  );
  if (outcome.action === "deny") return { block: true, reason: `[ai-eng] ${outcome.by}: ${outcome.reason}` };
  return {};
}
