"""Write the managed ``.ai-engineering/.gitignore`` on install.

``ai-eng install`` generates transient, per-install, and derived artifacts
under ``.ai-engineering/`` — append-only audit streams, per-install state
SoTs, the compiled & signed OPA bundle (``state/runtime/bundle.tar.gz``),
and per-install OPA signing outputs. None of those belong in version
control: they are machine-specific and rebuildable from the committed
sources of truth (``policies/*.rego``, ``manifest.yml``, ``specs/*.md``).

Without an ignore rule a consumer who runs ``git add`` commits a binary
signed with their local key (``~/.config/ai-engineering/opa-signing-key.pem``)
that no teammate can verify. This module ships a scoped
``.ai-engineering/.gitignore`` that ignores exactly those artifacts while
keeping the sources of truth — plus ``notes/``, the committed governance
store ``state/decision-store.json`` (risk acceptances are born there and
are not rebuildable from specs), and the ``state/hooks-manifest.json``
integrity baseline — tracked.

The file is written programmatically rather than copied from the template
tree because the wheel build only packages
``templates/**/*.{md,yml,json}`` (see ``[tool.hatch.build.targets.wheel]``
in ``pyproject.toml``); a dotfile named ``.gitignore`` has no matching
extension and would never reach a pip-installed consumer.
"""

from __future__ import annotations

from pathlib import Path

MANAGED_GITIGNORE_REL: Path = Path(".ai-engineering") / ".gitignore"
"""Destination path of the managed gitignore, relative to the project root."""

MANAGED_GITIGNORE_CONTENT: str = """\
# ---------------------------------------------------------------------------
# Managed by ai-engineering — rewritten by `ai-eng install`. Do not edit here.
# Ignores transient / per-install / derived artifacts under .ai-engineering/.
# Put project-specific ignore rules in your project-root .gitignore instead.
#
# Committed sources of truth (intentionally NOT ignored): policies/*.rego,
# manifest.yml, specs/*.md, notes/, state/decision-store.json (governance
# decisions + risk acceptances), state/hooks-manifest.json (the hook
# integrity baseline).
# ---------------------------------------------------------------------------

# Per-install state — machine-specific, regenerated by install + governance flows
state/install-state.json
state/ownership-map.json
state/framework-capabilities.json

# Append-only audit + observation streams (per-install)
state/framework-events.ndjson
state/observation-events.ndjson
state/instinct-observations.ndjson

# Instinct extraction watermark — per-session runtime state (spec-162 D-162-02)
observations/meta.json

# Derived database (per-user, rebuilt from the event stream)
state/state.db
state/state.db-wal
state/state.db-shm

# Transient gate / compaction artifacts + lock files
state/gate-findings.json
state/strategic-compact.json
state/locks/

# Runtime working dirs + compiled & signed OPA bundle (bundle.tar.gz lives here)
state/runtime/
runtime/
runs/

# Caches
cache/
.cache/

# Per-machine local config override
local.yml

# Per-install OPA signing outputs (the bundle they sign is ignored above)
policies/.signatures.json
policies/.manifest

# Secret-material safety net — never let key/credential files slip in
*.pem
*.key
*.p12
*.pfx
credentials*.json

# OS cruft inside the managed tree
.DS_Store
"""


def ensure_project_gitignore(
    project_root: Path,
    *,
    fresh: bool = False,
) -> dict[str, object]:
    """Write the managed ``.ai-engineering/.gitignore`` under *project_root*.

    Create-only by default: an existing file is preserved so operator edits
    survive a routine reinstall. When *fresh* is true (``InstallMode.FRESH``),
    the managed content is rewritten unconditionally.

    Returns a result dict with keys ``written`` (bool), ``action``
    (``"created"`` | ``"overwritten"`` | ``"skipped"``), and ``path`` (str).
    """
    dest = project_root / MANAGED_GITIGNORE_REL
    existed = dest.exists()

    if existed and not fresh:
        return {"written": False, "action": "skipped", "path": str(dest)}

    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(MANAGED_GITIGNORE_CONTENT, encoding="utf-8")
    return {
        "written": True,
        "action": "overwritten" if existed else "created",
        "path": str(dest),
    }
