import { ensureDir, resolvePath } from '../../utils/filesystem.js';
import { logger } from '../../utils/logger.js';
import type { IntermediateRepresentation } from '../assembler.js';

interface CopilotOutput {
  instructionsMd: string;
}

function buildCopilotInstructions(ir: IntermediateRepresentation): string {
  const sections: string[] = [];

  sections.push('# GitHub Copilot Instructions');
  sections.push('');
  sections.push(`> Generated by ai-engineering v${ir.config.version} on ${new Date().toISOString().split('T')[0]}`);
  sections.push(`> Stacks: ${ir.config.stacks.join(', ')} | Level: ${ir.config.level}`);
  sections.push('');

  // Critical rules
  sections.push('## Critical Rules');
  sections.push('');
  sections.push('These rules are absolute and must never be violated:');
  sections.push('');
  sections.push('- Never use `git push --force` or `git push -f`');
  sections.push(`- Never commit directly to protected branches: ${ir.config.branches.protectedBranches.join(', ')}`);
  sections.push('- Never commit `.env*`, `*.pem`, `*.key`, `credentials*`, or files containing secrets');
  sections.push('- Never use `--no-verify` on git commands');
  sections.push('- Never hardcode secrets, tokens, passwords, or API keys in source code');
  sections.push('- Always use conventional commit format: `<type>(<scope>): <description>`');
  sections.push('- Always run tests after code changes');
  sections.push('');

  // Branch rules
  sections.push('## Branch Compliance');
  sections.push('');
  sections.push(`Default branch: \`${ir.config.branches.defaultBranch}\``);
  sections.push(`Development branch: \`${ir.config.branches.developBranch}\``);
  sections.push('');
  sections.push('- Feature branches: `feature/<description>` or `dev/<name>/<description>`');
  sections.push('- Bug fix branches: `fix/<description>`');
  sections.push('- Hotfix branches: `hotfix/<description>`');
  sections.push('- Release branches: `release/<version>`');
  sections.push('');

  // Standards
  sections.push(ir.assembled.standards);
  sections.push('');

  // Security
  sections.push('## Security Standards');
  sections.push('');
  sections.push(ir.assembled.security);
  sections.push('');

  // Git
  sections.push('## Git Conventions');
  sections.push('');
  sections.push(ir.assembled.git);
  sections.push('');

  // Testing
  sections.push('## Testing Standards');
  sections.push('');
  sections.push(ir.assembled.testing);
  sections.push('');

  // Agent guidelines (embedded as instructions since Copilot doesn't have command system)
  sections.push('## Code Review Checklist');
  sections.push('');
  sections.push('When reviewing or writing code, check:');
  sections.push('1. Security: No OWASP top 10 vulnerabilities, no hardcoded secrets');
  sections.push('2. Quality: Error handling, edge cases, no dead code');
  sections.push('3. Patterns: Follows project conventions and stack standards');
  sections.push('4. Tests: Changes are tested, coverage maintained');
  sections.push('5. Performance: No unnecessary re-renders, N+1 queries, or blocking calls');
  sections.push('');

  // Simplification guidelines
  sections.push('## After Implementation');
  sections.push('');
  sections.push('After completing code changes, review for:');
  sections.push('- Unnecessary complexity or over-abstraction');
  sections.push('- Dead code introduced during iteration');
  sections.push('- Verbose patterns that can be simplified');
  sections.push('- Duplicated logic that should be extracted');
  sections.push('- Naming that could be clearer');
  sections.push('');

  // Multi-IDE Sync
  sections.push('## Multi-IDE Sync');
  sections.push('');
  sections.push('This project uses ai-engineering with section markers. If you modify the TEAM section');
  sections.push('of this file, check if other IDE instruction files exist and update their TEAM sections');
  sections.push('to keep them in sync:');
  sections.push('- `CLAUDE.md`');
  sections.push('- `codex.md`');

  return sections.join('\n');
}

export function compileCopilot(ir: IntermediateRepresentation): CopilotOutput {
  logger.info('Compiling GitHub Copilot target...');
  const instructionsMd = buildCopilotInstructions(ir);
  return { instructionsMd };
}

export function writeCopilotOutput(_output: CopilotOutput, projectRoot: string): void {
  const dir = resolvePath(projectRoot, '.github');
  ensureDir(dir);
  // Note: marked output is handled by compile() in index.ts
  logger.success('Generated .github/copilot-instructions.md');
}
