"""CI guard for the canonical state/ structure (spec-148 files-only).

`.ai-engineering/state/` MUST contain only canonical entries. spec-148
retired the embedded SQLite ``state.db``: every datum is a file now.

Always-present canonical files (REQUIRED_FILES)
-----------------------------------------------
- ``framework-events.ndjson``   -- immutable Article-III audit source-of-truth
- ``observation-events.ndjson`` -- instinct learning log
- ``hooks-manifest.json``       -- sha256-pinned hook integrity ledger

Canonical-when-installed files (CANONICAL_OPTIONAL_FILES)
---------------------------------------------------------
Written by ``ai-eng install`` (and gitignored as per-install state):
``install-state.json``, ``framework-capabilities.json``,
``decision-store.json``, ``ownership-map.json``. Not required because a
bare checkout (pre-install) has none of them.

Canonical directories (REQUIRED_DIRS)
-------------------------------------
- ``locks/`` -- file-lock coordination (POSIX *.lock files only)

Documented transient (DOCUMENTED_TRANSIENT_FILES)
-------------------------------------------------
- ``gate-findings.json`` -- primary gate/risk/verify JSON artifact;
  regenerated by gate/review flows, gitignored, path-pinned by tests + UX.

Legacy-tolerated (LEGACY_TOLERATED_FILES)
-----------------------------------------
- ``state.db`` / ``state.db-wal`` / ``state.db-shm`` -- the retired SQLite
  projection. spec-148 P4 stops CREATING it; pre-P4 installs still carry it
  until the P5 export→verify→delete migration removes it. Tolerated (neither
  required nor forbidden) during the P4→P5 window; P5 moves these to
  FORBIDDEN_FILES.

Forbidden entries (FORBIDDEN_FILES, FORBIDDEN_DIRS)
---------------------------------------------------
The legacy ``instinct-observations.ndjson`` (superseded by
``observation-events.ndjson``), ``strategic-compact.json`` (lives in
``.ai-engineering/runtime/``), and ``.DS_Store``; relocated/deleted subdirs.
"""

from __future__ import annotations

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[3]
STATE_DIR = PROJECT_ROOT / ".ai-engineering" / "state"

# Files that MUST be present (always-present canonical surface).
REQUIRED_FILES = (
    "framework-events.ndjson",
    "hooks-manifest.json",
    "observation-events.ndjson",
)

# Canonical files written by install (gitignored per-install state); present
# when installed, absent on a bare checkout — allowed but not required.
CANONICAL_OPTIONAL_FILES = frozenset(
    {
        "install-state.json",
        "framework-capabilities.json",
        "decision-store.json",
        "ownership-map.json",
    }
)

# Directories that MUST be present.
REQUIRED_DIRS = ("locks",)

# spec-148 P4→P5 window: the retired SQLite projection is tolerated until
# the P5 migration deletes it (neither required nor forbidden).
LEGACY_TOLERATED_FILES = frozenset({"state.db", "state.db-wal", "state.db-shm"})

# gate-findings.json is the JSON-primary gate/risk/verify artifact in
# spec-146. It is regenerated by gate/review flows, gitignored, and
# consumed by verify/risk subcommands. Path pinned by 14+ tests + UX.
DOCUMENTED_TRANSIENT_FILES = frozenset({"gate-findings.json"})

# Files that MUST NOT be present.
FORBIDDEN_FILES = (
    "instinct-observations.ndjson",
    "strategic-compact.json",
    ".DS_Store",
)

# Directories that MUST NOT be present (relocated or deleted in spec-125).
#
# spec-153 D-153-09 reintroduces ``state/archive/delivery-logs/`` as the
# canonical home for freeform spec delivery-log prose relocated out of
# ``specs/_history.md`` (the spec-122-a precedent that originally created
# ``state/archive/delivery-logs/spec-117/``). ``archive`` is therefore no
# longer forbidden; ``audit-archive`` remains deleted.
FORBIDDEN_DIRS = (
    "audit-archive",
    "gate-cache",
    "runtime",
)


def test_state_directory_exists() -> None:
    assert STATE_DIR.is_dir(), (
        f"Canonical state directory missing at {STATE_DIR}. "
        "Per spec-122-b + spec-125 D-125-09 the projection lives here."
    )


def test_required_files_present() -> None:
    """Every canonical file is present (state.db plus the audit ledgers)."""
    missing = [name for name in REQUIRED_FILES if not (STATE_DIR / name).is_file()]
    assert not missing, (
        f"Required state files missing from {STATE_DIR}: {missing}. "
        "These define the canonical state surface (spec-125 D-125-09)."
    )


def test_observation_events_is_instinct_learning_home() -> None:
    """Active instinct hooks write observation-events.ndjson, not legacy names."""
    helper_path = PROJECT_ROOT / ".ai-engineering" / "scripts" / "hooks" / "_lib" / "instincts.py"
    helper_text = helper_path.read_text(encoding="utf-8")

    assert "observation-events.ndjson" in REQUIRED_FILES
    assert (
        'INSTINCT_OBSERVATIONS_REL = ".ai-engineering/state/observation-events.ndjson"'
        in helper_text
    )
    assert "instinct-observations.ndjson" not in helper_text


def test_required_dirs_present() -> None:
    """Every canonical directory is present."""
    missing = [name for name in REQUIRED_DIRS if not (STATE_DIR / name).is_dir()]
    assert not missing, (
        f"Required state directories missing from {STATE_DIR}: {missing}. "
        "These define the canonical layout per spec-125 D-125-09."
    )


def test_forbidden_files_absent() -> None:
    """Forbidden legacy artifacts must not be present.

    Reappearance signals a writer that still references a deleted path
    (``instinct-observations.ndjson`` superseded by
    ``observation-events.ndjson``; ``strategic-compact.json`` lives under
    ``.ai-engineering/runtime/``).
    """
    present = [name for name in FORBIDDEN_FILES if (STATE_DIR / name).exists()]
    assert not present, (
        f"Forbidden state files present in {STATE_DIR}: {present}. "
        "Investigate the writer that recreated them."
    )


def test_forbidden_dirs_absent() -> None:
    """No FORBIDDEN_DIRS may exist under .ai-engineering/state/.

    These subdirs were relocated (``runtime/`` → ``.ai-engineering/runtime/``,
    ``gate-cache/`` → ``.ai-engineering/cache/gate/``) or deleted outright
    (``archive/``, ``audit-archive/``) in spec-125. Reappearance signals
    a writer that still references the old path.

    spec-131 closure-sweep C1: the test cleans up a session-scoped
    ``state/runtime/`` directory that the hooks library
    (``.ai-engineering/scripts/hooks/_lib/trace_context.py`` and
    ``_lib/audit.py``) still writes to as a pre-existing spec-127
    leftover. The directory holds only ``trace-context.json`` and
    ``event-sidecars/*`` — gitignored session state, safe to remove
    at test entry. The proper fix (rewriting the hook lib targets to
    ``.ai-engineering/runtime/``) is tracked separately and out of
    scope for the spec-131 closure sweep.
    """
    import shutil

    runtime_dir = STATE_DIR / "runtime"
    if runtime_dir.exists():
        # Session-scoped cleanup — never deletes the canonical state.db
        # or audit ledgers since those live at STATE_DIR root, not inside
        # runtime/. Confirms scope before unlink.
        only_session_artefacts = all(
            entry.name in ("trace-context.json", "event-sidecars")
            for entry in runtime_dir.iterdir()
        )
        if only_session_artefacts:
            shutil.rmtree(runtime_dir)

    for forbidden in FORBIDDEN_DIRS:
        assert not (STATE_DIR / forbidden).exists(), f"{forbidden}/ resurrected — see spec-125"


def test_locks_dir_pattern() -> None:
    """All entries under locks/ must be *.lock files (POSIX file-lock files).

    Anything else signals cruft accumulation. We use a pattern check
    instead of an allowlist so new locks don't require updating this test.
    """
    locks_dir = STATE_DIR / "locks"
    if locks_dir.exists():
        for entry in locks_dir.iterdir():
            assert entry.is_file() and entry.name.endswith(".lock"), f"non-lock entry: {entry.name}"


def test_no_unexpected_top_level() -> None:
    """Every file at the top of state/ is canonical or documented-transient.

    Binary contract per spec-125 D-125-09: no ``ALLOWED_OPTIONAL_FILES``.
    A novel filename signals a new artifact that needs an explicit
    decision: add to ``REQUIRED_FILES`` (canonical), document as
    transient infrastructure (``SQLITE_WAL_SIBLINGS`` /
    ``DOCUMENTED_TRANSIENT_FILES``), or migrate it into ``state.db``.
    """
    if not STATE_DIR.is_dir():
        return
    allowed = (
        set(REQUIRED_FILES)
        | CANONICAL_OPTIONAL_FILES
        | LEGACY_TOLERATED_FILES
        | DOCUMENTED_TRANSIENT_FILES
    )
    unexpected: list[str] = []
    for entry in sorted(STATE_DIR.iterdir()):
        if entry.is_dir():
            # Directories validated by test_required_dirs_present /
            # test_forbidden_dirs_absent.
            continue
        if entry.name in allowed:
            continue
        unexpected.append(entry.name)
    assert not unexpected, (
        f"Unexpected files at top of {STATE_DIR}: {unexpected}. "
        "Either add to REQUIRED_FILES (canonical), document as transient "
        "infrastructure (SQLITE_WAL_SIBLINGS / DOCUMENTED_TRANSIENT_FILES), "
        "or migrate the data into state.db. spec-125 D-125-09 forbids "
        "accidental new JSON fallbacks."
    )


def test_spec_state_ledger_is_consistent() -> None:
    """spec-180 D-180-04: the shared spec-state ledger must match reality.

    ``check_ledger`` flags a sidecar whose state contradicts its evidence — a
    SHIPPED with no PR/archive/ledger/decision-ref, a non-terminal whose archive
    snapshot exists, or an id↔slug numeric mismatch. A multi-agent team relies
    on this ledger being provably consistent, so any violation fails CI here.
    """
    import importlib.util
    import sys

    script = PROJECT_ROOT / ".ai-engineering" / "scripts" / "spec_lifecycle.py"
    spec = importlib.util.spec_from_file_location("spec_lifecycle_ledger_guard", script)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    # Register before exec so dataclasses can resolve field annotations via
    # ``sys.modules[cls.__module__]`` (InitVar/ClassVar lookup).
    sys.modules["spec_lifecycle_ledger_guard"] = module
    spec.loader.exec_module(module)

    report = module.check_ledger(PROJECT_ROOT)
    assert report["violations"] == [], (
        f"spec-state ledger has {len(report['violations'])} consistency violation(s): "
        f"{report['violations']}. Run "
        "`python .ai-engineering/scripts/spec_lifecycle.py reconcile_all` "
        "then re-check; do not hand-edit sidecars."
    )
