"""CI guard for the canonical state/ structure (spec-148 files-only).

`.ai-engineering/state/` MUST contain only canonical entries. spec-148
retired the embedded SQLite ``state.db``: every datum is a file now.

Always-present canonical files (REQUIRED_FILES)
-----------------------------------------------
- ``framework-events.ndjson``   -- immutable Article-III audit source-of-truth
- ``observation-events.ndjson`` -- instinct learning log
- ``hooks-manifest.json``       -- sha256-pinned hook integrity ledger

Canonical-when-installed files (CANONICAL_OPTIONAL_FILES)
---------------------------------------------------------
Written by ``ai-eng install`` (and gitignored as per-install state):
``install-state.json``, ``framework-capabilities.json``,
``decision-store.json``, ``ownership-map.json``. Not required because a
bare checkout (pre-install) has none of them.

Canonical directories (REQUIRED_DIRS)
-------------------------------------
- ``locks/`` -- file-lock coordination (POSIX *.lock files only)

Documented transient (DOCUMENTED_TRANSIENT_FILES)
-------------------------------------------------
- ``gate-findings.json`` -- primary gate/risk/verify JSON artifact;
  regenerated by gate/review flows, gitignored, path-pinned by tests + UX.

Legacy-tolerated (LEGACY_TOLERATED_FILES)
-----------------------------------------
- ``state.db`` / ``state.db-wal`` / ``state.db-shm`` -- the retired SQLite
  projection. spec-148 P4 stops CREATING it; pre-P4 installs still carry it
  until the P5 export→verify→delete migration removes it. Tolerated (neither
  required nor forbidden) during the P4→P5 window; P5 moves these to
  FORBIDDEN_FILES.

Forbidden entries (FORBIDDEN_FILES, FORBIDDEN_DIRS)
---------------------------------------------------
The legacy ``instinct-observations.ndjson`` (superseded by
``observation-events.ndjson``), ``strategic-compact.json`` (lives in
``.ai-engineering/runtime/``), and ``.DS_Store``; relocated/deleted subdirs.
"""

from __future__ import annotations

import ast
import itertools
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[3]
STATE_DIR = PROJECT_ROOT / ".ai-engineering" / "state"

# Files that MUST be present (always-present canonical surface).
REQUIRED_FILES = (
    "framework-events.ndjson",
    "hooks-manifest.json",
    "observation-events.ndjson",
)

# Canonical files written by install (gitignored per-install state); present
# when installed, absent on a bare checkout — allowed but not required.
CANONICAL_OPTIONAL_FILES = frozenset(
    {
        "install-state.json",
        "framework-capabilities.json",
        "decision-store.json",
        "ownership-map.json",
    }
)

# Directories that MUST be present.
REQUIRED_DIRS = ("locks",)

# spec-148 P4→P5 window: the retired SQLite projection is tolerated until
# the P5 migration deletes it (neither required nor forbidden).
LEGACY_TOLERATED_FILES = frozenset({"state.db", "state.db-wal", "state.db-shm"})

# gate-findings.json is the JSON-primary gate/risk/verify artifact in
# spec-146. It is regenerated by gate/review flows, gitignored, and
# consumed by verify/risk subcommands. Path pinned by 14+ tests + UX.
DOCUMENTED_TRANSIENT_FILES = frozenset({"gate-findings.json"})

# Files that MUST NOT be present.
FORBIDDEN_FILES = (
    "instinct-observations.ndjson",
    "strategic-compact.json",
    ".DS_Store",
)

# Directories that MUST NOT be present (relocated or deleted in spec-125).
#
# spec-153 D-153-09 reintroduces ``state/archive/delivery-logs/`` as the
# canonical home for freeform spec delivery-log prose relocated out of
# ``specs/_history.md`` (the spec-122-a precedent that originally created
# ``state/archive/delivery-logs/spec-117/``). ``archive`` is therefore no
# longer forbidden; ``audit-archive`` remains deleted.
FORBIDDEN_DIRS = (
    "audit-archive",
    "gate-cache",
    "runtime",
)


def test_state_directory_exists() -> None:
    assert STATE_DIR.is_dir(), (
        f"Canonical state directory missing at {STATE_DIR}. "
        "Per spec-122-b + spec-125 D-125-09 the projection lives here."
    )


def test_required_files_present() -> None:
    """Every canonical file is present (state.db plus the audit ledgers)."""
    missing = [name for name in REQUIRED_FILES if not (STATE_DIR / name).is_file()]
    assert not missing, (
        f"Required state files missing from {STATE_DIR}: {missing}. "
        "These define the canonical state surface (spec-125 D-125-09)."
    )


def test_observation_events_is_instinct_learning_home() -> None:
    """Active instinct hooks write observation-events.ndjson, not legacy names."""
    helper_path = PROJECT_ROOT / ".ai-engineering" / "scripts" / "hooks" / "_lib" / "instincts.py"
    helper_text = helper_path.read_text(encoding="utf-8")

    assert "observation-events.ndjson" in REQUIRED_FILES
    assert (
        'INSTINCT_OBSERVATIONS_REL = ".ai-engineering/state/observation-events.ndjson"'
        in helper_text
    )
    assert "instinct-observations.ndjson" not in helper_text


def test_required_dirs_present() -> None:
    """Every canonical directory is present."""
    missing = [name for name in REQUIRED_DIRS if not (STATE_DIR / name).is_dir()]
    assert not missing, (
        f"Required state directories missing from {STATE_DIR}: {missing}. "
        "These define the canonical layout per spec-125 D-125-09."
    )


def test_forbidden_files_absent() -> None:
    """Forbidden legacy artifacts must not be present.

    Reappearance signals a writer that still references a deleted path
    (``instinct-observations.ndjson`` superseded by
    ``observation-events.ndjson``; ``strategic-compact.json`` lives under
    ``.ai-engineering/runtime/``).
    """
    present = [name for name in FORBIDDEN_FILES if (STATE_DIR / name).exists()]
    assert not present, (
        f"Forbidden state files present in {STATE_DIR}: {present}. "
        "Investigate the writer that recreated them."
    )


def test_forbidden_dirs_absent() -> None:
    """No FORBIDDEN_DIRS may exist under .ai-engineering/state/.

    These subdirs were relocated (``runtime/`` → ``.ai-engineering/runtime/``,
    ``gate-cache/`` → ``.ai-engineering/cache/gate/``) or deleted outright
    (``archive/``, ``audit-archive/``) in spec-125. Reappearance signals
    a writer that still references the old path.

    spec-200 D-200-03 removed the tolerance workaround this test used to carry.
    It cleaned up ``state/runtime/`` at test entry when the directory held only
    ``trace-context.json`` or ``event-sidecars/``, because the hook library
    still wrote there. Two problems with that: it hid a live violation the test
    exists to catch, and its two-name allowlist silently stopped working when
    spec-190 added a third writer (``session-pointer.json``) — the cleanup was
    skipped and the assertion failed on correct code, which read as flakiness.

    Both are moot now: no writer targets the path, and the SessionEnd rotation
    reaper (``runtime_rotate._remove_legacy_runtime_dir``) removes an orphan
    left over from before the upgrade. The assertion stands on its own, so a
    future writer that resurrects the directory fails here — as intended.
    """
    for forbidden in FORBIDDEN_DIRS:
        assert not (STATE_DIR / forbidden).exists(), f"{forbidden}/ resurrected — see spec-125"


def test_locks_dir_pattern() -> None:
    """All entries under locks/ must be *.lock files (POSIX file-lock files).

    Anything else signals cruft accumulation. We use a pattern check
    instead of an allowlist so new locks don't require updating this test.
    """
    locks_dir = STATE_DIR / "locks"
    if locks_dir.exists():
        for entry in locks_dir.iterdir():
            assert entry.is_file() and entry.name.endswith(".lock"), f"non-lock entry: {entry.name}"


def test_no_unexpected_top_level() -> None:
    """Every file at the top of state/ is canonical or documented-transient.

    Binary contract per spec-125 D-125-09: no ``ALLOWED_OPTIONAL_FILES``.
    A novel filename signals a new artifact that needs an explicit
    decision: add to ``REQUIRED_FILES`` (canonical), document as
    transient infrastructure (``SQLITE_WAL_SIBLINGS`` /
    ``DOCUMENTED_TRANSIENT_FILES``), or migrate it into ``state.db``.
    """
    if not STATE_DIR.is_dir():
        return
    allowed = (
        set(REQUIRED_FILES)
        | CANONICAL_OPTIONAL_FILES
        | LEGACY_TOLERATED_FILES
        | DOCUMENTED_TRANSIENT_FILES
    )
    unexpected: list[str] = []
    for entry in sorted(STATE_DIR.iterdir()):
        if entry.is_dir():
            # Directories validated by test_required_dirs_present /
            # test_forbidden_dirs_absent.
            continue
        if entry.name in allowed:
            continue
        unexpected.append(entry.name)
    assert not unexpected, (
        f"Unexpected files at top of {STATE_DIR}: {unexpected}. "
        "Either add to REQUIRED_FILES (canonical), document as transient "
        "infrastructure (SQLITE_WAL_SIBLINGS / DOCUMENTED_TRANSIENT_FILES), "
        "or migrate the data into state.db. spec-125 D-125-09 forbids "
        "accidental new JSON fallbacks."
    )


def test_spec_state_ledger_is_consistent() -> None:
    """spec-180 D-180-04: the shared spec-state ledger must match reality.

    ``check_ledger`` flags a sidecar whose state contradicts its evidence — a
    SHIPPED with no PR/archive/ledger/decision-ref, a non-terminal whose archive
    snapshot exists, or an id↔slug numeric mismatch. A multi-agent team relies
    on this ledger being provably consistent, so any violation fails CI here.
    """
    import importlib.util
    import sys

    script = PROJECT_ROOT / ".ai-engineering" / "scripts" / "spec_lifecycle.py"
    spec = importlib.util.spec_from_file_location("spec_lifecycle_ledger_guard", script)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    # Register before exec so dataclasses can resolve field annotations via
    # ``sys.modules[cls.__module__]`` (InitVar/ClassVar lookup).
    sys.modules["spec_lifecycle_ledger_guard"] = module
    spec.loader.exec_module(module)

    report = module.check_ledger(PROJECT_ROOT)
    assert report["violations"] == [], (
        f"spec-state ledger has {len(report['violations'])} consistency violation(s): "
        f"{report['violations']}. Run "
        "`python .ai-engineering/scripts/spec_lifecycle.py reconcile_all` "
        "then re-check; do not hand-edit sidecars."
    )


# ---------------------------------------------------------------------------
# spec-200 D-200-03: the forbidden path has no live resolver anywhere
# ---------------------------------------------------------------------------

# Files allowed to name the retired path in CODE, each for a stated reason.
#
# ``installer/gitignore.py`` emits a ``state/runtime/`` ignore rule so a
# consumer whose orphan has not been reaped yet keeps it untracked — an ignore
# rule, not a path resolution.
#
# ``scripts/runtime_rotate.py`` is the reaper: deleting the orphan requires
# naming it. It is the one module whose correctness depends on knowing the old
# location, and ``tests/unit/test_runtime_rotate_state_db.py`` pins its scope.
_LEGACY_RUNTIME_EXEMPT = (
    "installer/gitignore.py",
    "scripts/runtime_rotate.py",
)

_LIVE_CODE_ROOTS = (
    PROJECT_ROOT / "src",
    PROJECT_ROOT / ".ai-engineering" / "scripts",
)


def _string_constants(node: ast.AST, docstrings: set[int]) -> list[str]:
    """String literals inside ``node`` in SOURCE order, skipping docstrings.

    Sorted by position because ``ast.walk`` is breadth-first: walking the
    ``Path(...) / "state" / "runtime" / "x"`` chain yields the leaves out of
    source order, which silently defeats the adjacency check below and makes
    this whole guard vacuous.
    """
    found = [
        child
        for child in ast.walk(node)
        if isinstance(child, ast.Constant)
        and isinstance(child.value, str)
        and id(child) not in docstrings
    ]
    found.sort(key=lambda c: (getattr(c, "lineno", 0), getattr(c, "col_offset", 0)))
    return [child.value for child in found]


def _docstring_ids(tree: ast.AST) -> set[int]:
    """Identity set of every docstring Constant node in ``tree``.

    Prose may discuss the retired path freely — the comments explaining why it
    was retired are the main reason this exclusion exists. Only code that
    *builds* the path is a defect.
    """
    holders = (ast.Module, ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)
    out: set[int] = set()
    for node in ast.walk(tree):
        if not isinstance(node, holders):
            continue
        body = getattr(node, "body", [])
        if not body or not isinstance(body[0], ast.Expr):
            continue
        value = body[0].value
        if isinstance(value, ast.Constant) and isinstance(value.value, str):
            out.add(id(value))
    return out


def _resolves_legacy_runtime(source: str) -> bool:
    """True when *source* contains code that builds ``state/runtime``.

    Catches both spellings the codebase used: the ``Path`` division chain
    (``Path(".ai-engineering") / "state" / "runtime"``) and the tuple form
    (``(".ai-engineering", "state", "runtime", ...)``) — in each case ``"state"``
    is immediately followed by ``"runtime"`` in the expression's literals — plus
    a single literal that embeds the joined path.
    """
    try:
        tree = ast.parse(source)
    except SyntaxError:  # pragma: no cover - unparseable file is not a hit
        return False
    docstrings = _docstring_ids(tree)
    for node in ast.walk(tree):
        if not isinstance(node, (ast.BinOp, ast.Tuple, ast.List, ast.Call)):
            continue
        literals = _string_constants(node, docstrings)
        for first, second in itertools.pairwise(literals):
            if first == "state" and second == "runtime":
                return True
    for node in ast.walk(tree):
        if (
            isinstance(node, ast.Constant)
            and isinstance(node.value, str)
            and id(node) not in docstrings
            and "state/runtime" in node.value
        ):
            return True
    return False


def test_no_live_code_resolves_legacy_runtime_path() -> None:
    """No writer, reader, or constant may build ``.ai-engineering/state/runtime``.

    spec-125 relocated the runtime subtree to ``.ai-engineering/runtime/`` but
    left ten sites behind — five live hook resolvers, nine dead ``*_REL``
    re-exports across two modules, and three package-side installer sites.
    spec-200 D-200-03 retires all of them, and this guard is what stops the path
    returning: ``test_forbidden_dirs_absent`` only catches a writer that already
    ran on this machine, which is how the leftovers survived two specs of CI.

    Parses code rather than grepping text, so the comments documenting the
    retirement are free and only a real path construction fails. Scoped to
    shipped code (``src/`` including the installer template tree, and the
    canonical script tree); tests may name the path to assert its absence, and
    CHANGELOG plus archived specs are frozen history.
    """
    offenders: list[str] = []
    for root in _LIVE_CODE_ROOTS:
        if not root.is_dir():
            continue
        for path in sorted(root.rglob("*.py")):
            rel = path.relative_to(PROJECT_ROOT).as_posix()
            if any(rel.endswith(exempt) for exempt in _LEGACY_RUNTIME_EXEMPT):
                continue
            try:
                source = path.read_text(encoding="utf-8")
            except OSError:  # pragma: no cover - unreadable file is not a hit
                continue
            if _resolves_legacy_runtime(source):
                offenders.append(rel)

    assert not offenders, (
        "live code still resolves the forbidden .ai-engineering/state/runtime/ "
        f"path ({len(offenders)} file(s)): {offenders}. The canonical location "
        "is .ai-engineering/runtime/ — hook-side code goes through "
        "hook_context.RUNTIME_DIR(project_root). spec-200 D-200-03."
    )
