"""CI guard for spec-124 D-124-12: canonical state/ structure.

`.ai-engineering/state/` MUST contain only canonical entries after
the spec-124 wave 5 cleanup deleted the migrated JSON fallbacks.

Canonical files
---------------
- ``state.db`` -- unified SQLite projection (spec-122-b D-122-06)
- ``framework-events.ndjson`` -- immutable Article-III source-of-truth
- ``instinct-observations.ndjson`` -- instinct learning log
- ``hooks-manifest.json`` -- sha256-pinned hook integrity ledger

Canonical directories
---------------------
- ``archive/``        -- historical state snapshots
- ``audit-archive/``  -- rotated NDJSON audit logs
- ``gate-cache/``     -- gate run cache (spec-104)
- ``locks/``          -- file-lock coordination
- ``runtime/``        -- session-scoped runtime state (gitignored)

Optional artifacts (allowed when present)
-----------------------------------------
- ``state.db-shm`` / ``state.db-wal`` -- SQLite WAL artifacts
- ``install-state.json``        -- KEPT this wave; deletion deferred to spec-125
- ``framework-capabilities.json`` -- KEPT this wave; deletion deferred to spec-125
- ``.DS_Store``                 -- macOS metadata (best-effort ignored)
- ``gate-findings.json``        -- transient gate artifact (gitignored, may regenerate)

Forbidden entries (spec-124 D-124-12)
-------------------------------------
- ``decision-store.json`` -- migrated to state.db.decisions
- ``ownership-map.json``  -- migrated to state.db.ownership_map

When ``gate-findings.json`` regenerates on disk it is gitignored;
the test tolerates its presence but verifies it is not tracked.
"""

from __future__ import annotations

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[3]
STATE_DIR = PROJECT_ROOT / ".ai-engineering" / "state"

# Files that MUST be present (canonical surface).
REQUIRED_FILES = (
    "framework-events.ndjson",
    "hooks-manifest.json",
    "instinct-observations.ndjson",
    "state.db",
)

# Directories that MUST be present.
REQUIRED_DIRS = (
    "archive",
    "audit-archive",
    "gate-cache",
    "locks",
    "runtime",
)

# Files that MUST NOT be present (deprecated, deleted in spec-124 wave 5).
# `gate-findings.json` is allowed because it is gitignored and regenerated
# by every gate run; the .gitignore entry guarantees it never gets committed.
FORBIDDEN_FILES = (
    "decision-store.json",
    "ownership-map.json",
)

# Optional files / artifacts allowed when present.
ALLOWED_OPTIONAL_FILES = frozenset(
    {
        # SQLite WAL artifacts (transient; SQLite manages lifecycle).
        "state.db-shm",
        "state.db-wal",
        # Spec-124 wave 5 safety valve: kept this wave; spec-125 deletes.
        "install-state.json",
        "framework-capabilities.json",
        # Transient: gitignored, regenerated by gate runs.
        "gate-findings.json",
        # macOS metadata file (best-effort tolerated).
        ".DS_Store",
    }
)


def test_state_directory_exists() -> None:
    assert STATE_DIR.is_dir(), (
        f"Canonical state directory missing at {STATE_DIR}. "
        "Per spec-122-b + spec-124 D-124-12 the projection lives here."
    )


def test_required_files_present() -> None:
    """Every canonical file is present (state.db plus the audit ledgers)."""
    missing = [name for name in REQUIRED_FILES if not (STATE_DIR / name).is_file()]
    assert not missing, (
        f"Required state files missing from {STATE_DIR}: {missing}. "
        "These define the canonical state surface (spec-124 D-124-12)."
    )


def test_required_dirs_present() -> None:
    """Every canonical directory is present."""
    missing = [name for name in REQUIRED_DIRS if not (STATE_DIR / name).is_dir()]
    assert not missing, (
        f"Required state directories missing from {STATE_DIR}: {missing}. "
        "These define the canonical layout per spec-124 D-124-12."
    )


def test_forbidden_files_absent() -> None:
    """The deprecated JSON fallbacks must not be present.

    Reappearance indicates either (a) a regression in the wave 5 cleanup,
    (b) a manual write that bypasses ``state.db``, or (c) a missing
    ``.gitignore`` entry. State.db is canonical; the JSON projections
    were migrated in spec-122-b/spec-123 and deleted in spec-124 wave 5.
    """
    present = [name for name in FORBIDDEN_FILES if (STATE_DIR / name).exists()]
    assert not present, (
        f"Deprecated JSON fallbacks still present in {STATE_DIR}: {present}. "
        "spec-124 D-124-12 deleted these; their reappearance breaks the canonical "
        "contract. Investigate the writer that recreated them. "
        "Source-of-truth is state.db (decisions, ownership_map tables)."
    )


def test_no_unexpected_files() -> None:
    """Every file at the top of state/ is canonical, optional, or forbidden.

    A novel filename signals a new artifact that needs an explicit decision:
    add to ``REQUIRED_FILES`` (canonical), to ``ALLOWED_OPTIONAL_FILES``
    (transient/optional), or migrate it into ``state.db``.
    """
    if not STATE_DIR.is_dir():
        return
    canonical = set(REQUIRED_FILES)
    forbidden = set(FORBIDDEN_FILES)
    allowed_optional = ALLOWED_OPTIONAL_FILES
    unexpected: list[str] = []
    for entry in sorted(STATE_DIR.iterdir()):
        if entry.is_dir():
            # Directories validated separately by test_required_dirs_present.
            continue
        name = entry.name
        if name in canonical or name in forbidden or name in allowed_optional:
            continue
        unexpected.append(name)
    assert not unexpected, (
        f"Unexpected files at top of {STATE_DIR}: {unexpected}. "
        "Either add to REQUIRED_FILES (canonical), ALLOWED_OPTIONAL_FILES "
        "(transient artifact), or migrate the data into state.db. "
        "spec-124 D-124-12 forbids accidental new JSON fallbacks."
    )
