name: ai-eng-check
# Generated by ai-eng init — the CI gate. spec run fails when a CHECK could not run:
# green-by-absence-of-executor is impossible (§09.3).
#
# Two rules this file obeys on purpose:
#   · the governor is the *released binary*, pinned by version + sha256, so the
#     project needs no runtime for it and the version is bumped deliberately;
#   · every action is pinned by commit SHA — a tag is mutable, a SHA is not, and
#     this workflow is the one an agent is told not to touch (§17).
on: [push, pull_request]

env:
  AI_ENG_VERSION: v2.0.0-rc.1

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0

      - name: Install the governor (released binary, checksum-verified)
        run: |
          set -euo pipefail
          base="https://github.com/arcasilesgroup/ai-engineering/releases/download/${AI_ENG_VERSION}"
          curl -sSfL -o ai-eng "$base/ai-eng-linux-x64"
          curl -sSfL -o CHECKSUMS-SHA256.txt "$base/CHECKSUMS-SHA256.txt"
          grep 'ai-eng-linux-x64' CHECKSUMS-SHA256.txt | awk '{print $1"  ai-eng"}' | sha256sum -c -
          chmod +x ai-eng
          sudo install ai-eng /usr/local/bin/ai-eng

      - name: Install the canon the contract runner reads (machine side, no repo files)
        run: ai-eng init --global --yes

      - name: Dependencies (only when the project is a JavaScript one)
        run: |
          set -euo pipefail
          if [ -f bun.lock ] || [ -f bun.lockb ]; then bun install --frozen-lockfile
          elif [ -f package.json ]; then echo "package.json without a bun lockfile — install with your own package manager step"
          else echo "no package.json — the project brings its own runtime"; fi

      # --if-present skips a script the project does not declare (exit 0) and
      # propagates the failure of one it does. Nothing here swallows a failure:
      # a step that cannot fail is decoration.
      - name: Typecheck
        run: bun run --if-present typecheck
      - name: Lint
        run: bun run --if-present lint
      - name: Tests
        run: bun run --if-present test
      - name: Architecture
        run: bun run --if-present arch

      - name: Spec run (contract gates — the one step that must not be skipped)
        run: ai-eng spec run

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: gitleaks (pinned by version + sha256)
        run: |
          set -euo pipefail
          ver=8.30.0
          curl -sSfL -o gitleaks.tgz "https://github.com/gitleaks/gitleaks/releases/download/v${ver}/gitleaks_${ver}_linux_x64.tar.gz"
          echo "79a3ab579b53f71efd634f3aaf7e04a0fa0cf206b7ed434638d1547a2470a66e  gitleaks.tgz" | sha256sum -c -
          tar -xzf gitleaks.tgz gitleaks
          ./gitleaks detect --redact -v --no-banner

      # --config p/ci, never `auto`: auto refuses to run with metrics off, and a
      # governance gate that phones home is not a governance gate.
      - name: semgrep (pinned, no telemetry)
        run: |
          pipx install semgrep==1.172.0
          semgrep scan --error --config p/ci --metrics=off

      - name: trivy (pinned by commit SHA)
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          scan-type: fs
          exit-code: 1
          severity: HIGH,CRITICAL
