name: ai-eng-check
# Generated by ai-eng init — the CI gate. spec run fails when a CHECK could not run:
# green-by-absence-of-executor is impossible (§09.3).
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - name: Typecheck
        run: bun run typecheck
      - name: Lint
        run: bun run lint
      - name: Tests
        run: bun test
      - name: Spec run (contract gates)
        run: ai-eng spec run
      - name: Architecture
        run: bun run arch

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gitleaks (pinned)
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.30.0/gitleaks_8.30.0_linux_x64.tar.gz | tar xz
          ./gitleaks detect --no-git --redact -v
      - name: semgrep (pinned)
        run: |
          pipx install semgrep==1.126.0
          semgrep scan --error --config auto
      - name: trivy (pinned)
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: fs
          exit-code: 1
          severity: HIGH,CRITICAL
