// .opencode/plugins/ai-eng.ts — generated by ai-eng init. LOCAL plugin, never a
// remote npm package: OpenCode installs npm plugins with Bun at boot, and
// `"plugin": ["package"]` is arbitrary third-party execution (§13). Import in-process,
// zero spawn, deny = throw. checkpoint-gate.py runs beside the chain (not instead).
import { spawnSync } from "node:child_process";
import { homedir } from "node:os";
import { join } from "node:path";
import { chain } from "./ai-eng-chain.ts";

type ToolCall = { tool: string; input: Record<string, unknown>; sessionID?: string; callID?: string };

function checkpointGate(payload: Record<string, unknown>): void {
  const script = join(homedir(), ".ai-engineering", "scripts", "checkpoint-gate.py");
  const run = spawnSync("python3", [script, "--surface", "opencode"], { input: JSON.stringify(payload), encoding: "utf8" });
  if (run.status === 2) throw new Error(`[checkpoint-gate] ${(run.stderr || "blocked").trim()}`);
}

export async function beforeToolCall(call: ToolCall): Promise<ToolCall> {
  const payload = {
    tool_name: call.tool,
    tool_input: call.input,
    session_id: call.sessionID,
    tool_use_id: call.callID,
    cwd: process.cwd(),
  };
  checkpointGate(payload);
  const outcome = chain("PreToolUse", payload, { surface: "opencode" });
  if (outcome.action === "deny") throw new Error(`[ai-eng] ${outcome.by}: ${outcome.reason}`);
  if (outcome.action === "rewrite") return { ...call, input: { ...call.input, command: outcome.command } };
  return call;
}

export async function afterToolCall(call: ToolCall, result: unknown): Promise<unknown> {
  const payload = {
    tool_name: call.tool,
    tool_input: call.input,
    tool_response: result,
    session_id: call.sessionID,
    tool_use_id: call.callID,
  };
  const outcome = chain("PostToolUse", payload, { surface: "opencode" });
  if (outcome.action === "deny") throw new Error(`[ai-eng] ${outcome.by}: ${outcome.reason}`);
  return result;
}
