// .opencode/plugins/ai-eng.ts — generated by ai-eng init. LOCAL plugin, never a
// remote npm package: OpenCode installs npm plugins with Bun at boot, and
// `"plugin": ["package"]` is arbitrary third-party execution (§13). Import in-process,
// zero spawn, deny = throw.
import { chain } from "./ai-eng-chain.ts";

type ToolCall = { tool: string; input: Record<string, unknown>; sessionID?: string; callID?: string };

export async function beforeToolCall(call: ToolCall): Promise<ToolCall> {
  const payload = {
    tool_name: call.tool,
    tool_input: call.input,
    session_id: call.sessionID,
    tool_use_id: call.callID,
  };
  const outcome = chain("PreToolUse", payload, { surface: "opencode", dialect: "in-process" });
  if (outcome.action === "deny") throw new Error(`[ai-eng] ${outcome.by}: ${outcome.reason}`);
  if (outcome.action === "rewrite") return { ...call, input: { ...call.input, command: outcome.command } };
  return call;
}

export async function afterToolCall(call: ToolCall, result: unknown): Promise<unknown> {
  const payload = {
    tool_name: call.tool,
    tool_input: call.input,
    tool_response: result,
    session_id: call.sessionID,
    tool_use_id: call.callID,
  };
  const outcome = chain("PostToolUse", payload, { surface: "opencode", dialect: "in-process" });
  if (outcome.action === "deny") throw new Error(`[ai-eng] ${outcome.by}: ${outcome.reason}`);
  return result;
}
