// ~/.omp/agent/hooks/pre/ai-eng.ts — generated by ai-eng. In-process hook factory:
// OMP discovers <agentDir>/hooks/pre/*.ts and loads the module's DEFAULT export as the
// factory (omp://hooks.md, and a live probe on omp 18.1.17 — this path loads and blocks,
// `.agents/hooks/` loads nothing). deny = { block: true, reason }, argument mutation =
// rewrite, zero spawn for the chain. checkpoint-gate.py runs beside the chain (not instead).
// It sits on the machine, so it governs every repo that declares itself, and no repo
// carries a copy.
import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { chain } from "./.ai-eng-chain.ts";

type ToolCall = { toolName: string; input: Record<string, unknown>; sessionID?: string; callID?: string };
type Part = { type?: string; text?: string };

/** The tool's own output as text: the injection guard's containment arm reads it. */
function textOf(content: ReadonlyArray<Part> | undefined): string {
  return (content ?? []).map((part) => (typeof part.text === "string" ? part.text : "")).join("\n");
}

function checkpointGate(payload: Record<string, unknown>): { block: true; reason: string } | undefined {
  const script = join(homedir(), ".ai-engineering", "scripts", "checkpoint-gate.py");
  // Beside the chain, never instead: a missing script is no gate, not a denial.
  if (!existsSync(script)) return undefined;
  const run = spawnSync("python3", [script, "--surface", "oh-my-pi"], { input: JSON.stringify(payload), encoding: "utf8" });
  if (run.status === 2) return { block: true, reason: `[checkpoint-gate] ${(run.stderr || "blocked").trim()}` };
  return undefined;
}

export default function (pi: { on: (event: string, handler: (event: never, ctx: never) => unknown) => void }): void {
  pi.on("tool_call", (event, ctx) => {
    const call = event as unknown as ToolCall;
    const context = ctx as unknown as { cwd?: string };
    const payload = { tool_name: call.toolName, tool_input: call.input, session_id: call.sessionID, tool_use_id: call.callID, cwd: context.cwd };
    const gated = checkpointGate(payload);
    if (gated) return gated;
    const outcome = chain(
      "PreToolUse",
      // The host's own cwd rides along: the gate asks the repo that is actually being
      // worked in, not the one this process happens to sit in.
      payload,
      { surface: "oh-my-pi" },
    );
    if (outcome.action === "deny") return { block: true, reason: `[ai-eng] ${outcome.by}: ${outcome.reason}` };
    if (outcome.action === "rewrite") return { input: { ...call.input, command: outcome.command } };
    return undefined;
  });

  pi.on("tool_result", (event, ctx) => {
    const call = event as unknown as ToolCall & { content?: ReadonlyArray<Part> };
    const context = ctx as unknown as { cwd?: string };
    const outcome = chain(
      "PostToolUse",
      { tool_name: call.toolName, tool_input: call.input, tool_response: textOf(call.content), session_id: call.sessionID, tool_use_id: call.callID, cwd: context.cwd },
      { surface: "oh-my-pi" },
    );
    if (outcome.action === "deny") {
      // Containment, not prevention: the tool already ran, so the payload is replaced
      // with the reason instead of the injected text reaching the model.
      return { content: [{ type: "text", text: `[ai-eng] ${outcome.by}: ${outcome.reason}` }], isError: true };
    }
    return undefined;
  });
}
