// .pi/extensions/ai-eng.ts — generated by ai-eng init (pi). In-process module:
// deny = { block: true, reason }, argument mutation = rewrite, zero spawn.
// Measured against pi-coding-agent 0.85.1 (docs/extensions.md: "tool_call … Can block").
// pi sends lowercase tool names; the guards match them by name, so the spelling map
// lives in the chain's payload normaliser with the other hosts'. Project-local
// extensions load once pi trusts the folder (it asks; --approve pre-answers).
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { chain } from "./ai-eng-chain.ts";

/** The tool's own output as text: the injection guard's containment arm reads it. */
function textOf(content: ReadonlyArray<{ type?: string; text?: string }>): string {
  return content.map((part) => (typeof part.text === "string" ? part.text : "")).join("\n");
}

export default function (pi: ExtensionAPI): void {
  pi.on("tool_call", (event, ctx) => {
    const outcome = chain(
      "PreToolUse",
      { tool_name: event.toolName, tool_input: event.input, tool_use_id: event.toolCallId, cwd: ctx.cwd },
      { surface: "pi" },
    );
    if (outcome.action === "deny") return { block: true, reason: `[ai-eng] ${outcome.by}: ${outcome.reason}` };
    // pi applies input mutations to the real tool call — that is the rewrite arm.
    if (outcome.action === "rewrite") event.input["command"] = outcome.command;
    return;
  });

  pi.on("tool_result", (event, ctx) => {
    const outcome = chain(
      "PostToolUse",
      { tool_name: event.toolName, tool_input: event.input, tool_response: textOf(event.content), tool_use_id: event.toolCallId, cwd: ctx.cwd },
      { surface: "pi" },
    );
    if (outcome.action === "deny") {
      // Containment, not prevention: the tool already ran, so the payload is replaced
      // with the reason instead of the injected text reaching the model.
      return { content: [{ type: "text", text: `[ai-eng] ${outcome.by}: ${outcome.reason}` }], isError: true };
    }
    return;
  });
}
