{
  "$comment": "Generated by ai-eng init. Your own hooks, permissions and env are merged around, never overwritten.",
  "hooks": {
    "PreToolUse": [
      {
        "matcher": "Bash|PowerShell|Edit|Write|MultiEdit|Read|NotebookEdit|NotebookRead",
        "hooks": [{ "type": "command", "command": "ai-eng chain PreToolUse", "timeout": 5 }]
      }
    ],
    "PostToolUse": [
      {
        "matcher": "Bash|Edit|Write|MultiEdit|WebFetch|WebSearch",
        "hooks": [{ "type": "command", "command": "ai-eng chain PostToolUse", "timeout": 5 }]
      }
    ]
  }
}
