{
  "$comment": "Generated by ai-eng init. Merge kept 3-way: your own hooks stay.",
  "hooks": {
    "PreToolUse": [
      {
        "matcher": "Bash|PowerShell|Edit|Write|MultiEdit|Read|NotebookEdit|NotebookRead",
        "hooks": [{ "type": "command", "command": "ai-eng chain PreToolUse", "timeout": 5 }]
      }
    ],
    "PostToolUse": [
      {
        "matcher": "Bash|Edit|Write|MultiEdit|WebFetch|WebSearch",
        "hooks": [{ "type": "command", "command": "ai-eng chain PostToolUse", "timeout": 5 }]
      }
    ],
    "Stop": [
      { "hooks": [{ "type": "command", "command": "ai-eng chain Stop", "timeout": 5 }] }
    ],
    "SessionStart": [
      { "hooks": [{ "type": "command", "command": "ai-eng chain SessionStart", "timeout": 5 }] }
    ]
  }
}
