{
  "$comment": "Generated by ai-eng init. Your own hooks, permissions and env are merged around, never overwritten.",
  "hooks": {
    "PreToolUse": [
      {
        "matcher": "Bash|PowerShell|Edit|Write|MultiEdit|Read|NotebookEdit|NotebookRead|Agent|Task",
        "hooks": [
          {
            "type": "command",
            "command": "ai-eng chain PreToolUse",
            "timeout": 5
          },
          {
            "type": "command",
            "command": "python3 \"$HOME/.ai-engineering/scripts/checkpoint-gate.py\" --surface claude-code",
            "timeout": 5
          }
        ]
      }
    ],
    "Stop": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "python3 \"$HOME/.ai-engineering/scripts/checkpoint-gate.py\" --surface claude-code",
            "timeout": 5
          }
        ]
      }
    ],
    "PostToolUse": [
      {
        "matcher": "Bash|Edit|Write|MultiEdit|WebFetch|WebSearch",
        "hooks": [
          {
            "type": "command",
            "command": "ai-eng chain PostToolUse",
            "timeout": 5
          }
        ]
      }
    ],
    "UserPromptSubmit": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "ai-eng chain UserPromptSubmit",
            "timeout": 5
          }
        ]
      }
    ]
  }
}
