"""PR review command group."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Annotated

import typer

from ai_engineering.cli_envelope import emit_error, emit_success
from ai_engineering.cli_output import is_json_mode
from ai_engineering.cli_ui import error, success, warning
from ai_engineering.paths import resolve_project_root
from ai_engineering.vcs.factory import get_provider
from ai_engineering.vcs.protocol import VcsContext


def review_pr(
    target: Annotated[
        Path | None,
        typer.Argument(help="Target project root. Defaults to cwd."),
    ] = None,
    strict: Annotated[
        bool,
        typer.Option("--strict", help="Exit non-zero when provider review posting fails."),
    ] = False,
    findings_json: Annotated[
        Path | None,
        typer.Option(
            "--findings-json",
            help="Optional findings JSON file; high/critical findings are merge-blocking.",
        ),
    ] = None,
) -> None:
    """Post a headless PR review message through the configured VCS provider."""
    root = resolve_project_root(target)
    provider = get_provider(root)
    ctx = VcsContext(project_root=root)
    body = (
        "ai-eng automated review\n\n"
        "- High/Critical findings are merge-blocking\n"
        "- Review generated by governed CI flow\n"
    )

    severities = _load_findings(findings_json)
    if severities["high"] > 0 or severities["critical"] > 0:
        if is_json_mode():
            emit_error(
                "ai-eng review pr",
                f"Merge-blocking findings detected "
                f"(critical={severities['critical']}, high={severities['high']})",
                "BLOCKING_FINDINGS",
                "Resolve critical/high findings before merging",
            )
        else:
            error(
                f"Merge-blocking findings detected "
                f"(critical={severities['critical']}, high={severities['high']})"
            )
        raise typer.Exit(code=1)

    result = provider.post_pr_review(ctx, body=body)
    if result.success:
        if is_json_mode():
            emit_success(
                "ai-eng review pr",
                {"posted": True, "blocking_findings": severities},
            )
        else:
            success("PR review posted")
        return

    if is_json_mode():
        emit_error(
            "ai-eng review pr",
            f"PR review not posted: {result.output}",
            "POST_FAILED",
            "Check VCS provider configuration",
        )
    else:
        warning(f"PR review not posted: {result.output}")
    if strict:
        raise typer.Exit(code=1)


def _load_findings(path: Path | None) -> dict[str, int]:
    """Load finding severities from a JSON report."""
    counts = {"critical": 0, "high": 0}
    if path is None or not path.exists():
        return counts
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return counts

    findings = data.get("findings", []) if isinstance(data, dict) else []
    for finding in findings:
        if not isinstance(finding, dict):
            continue
        severity = str(finding.get("severity", "")).lower()
        if severity in counts:
            counts[severity] += 1
    return counts
