// Generator for src/assets.ts: embeds every skills/ and templates/ file into the
// binary as Bun file imports. The binary IS the payload (blueprint 07). Run:
//   bun scripts/gen-assets.ts
// Also bundles src/chain for in-process plugin hosts (P0-2, 2026-09-01): the
// OMP/OpenCode plugin templates import ./ai-eng-chain.ts, which must be a
// self-contained module — not a re-export of src/ (its relative imports die in
// a foreign repo) and not a placeholder comment (the plugin never loaded).
import { readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join, relative } from "node:path";

const root = join(import.meta.dir, "..");
const files: string[] = [];
function walk(dir: string): void {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) walk(full);
    else files.push(full);
  }
}

// ── the chain bundle FIRST: it must exist before the walk embeds it ──
// src/chain + a host-safe chain() wrapper, one self-contained file under
// skills/.chain-bundle/ (P0-2: the OMP/OpenCode plugin imports it as a module;
// a placeholder comment meant the plugin never loaded).
const { execSync } = await import("node:child_process");
const bundleDir = join(root, "skills", ".chain-bundle");
mkdirSync(bundleDir, { recursive: true });
execSync(`bun build scripts/chain-entry.ts --target=bun --format=esm --outfile=${JSON.stringify(join(bundleDir, "ai-eng-chain.ts"))}`, {
  cwd: root,
  stdio: "inherit",
});

walk(join(root, "skills"));
walk(join(root, "templates"));
// .json stays embeddable (P0-3): ai-security's report-schema.json is read at
// runtime by validate-findings.cjs; excluding it shipped a broken validator.
// .ts/.tsx stay out EXCEPT the chain bundle itself.
const chainPrefix = bundleDir + "/";
const embeddable = files.filter((f) => {
  if (f.endsWith(".DS_Store")) return false;
  if (f.startsWith(chainPrefix)) return f.endsWith(".ts");
  return !f.endsWith(".ts") && !f.endsWith(".tsx");
});

let out = "// GENERATED by scripts/gen-assets.ts - do not edit. The binary IS the payload (blueprint 07):\n// every skill and template travels inside it. Regenerate with: bun scripts/gen-assets.ts\n\n";

const lines: string[] = [];
const map: string[] = [];
for (const file of embeddable) {
  const rel = relative(root, file);
  const ident = "a" + rel.replace(/[^a-zA-Z0-9]/g, "_");
  lines.push(`import ${ident} from "../${rel}" with { type: "file" };`);
  map.push(`  "../${rel}": ${ident},`);
}
out += lines.join("\n") + "\n\nexport const EMBEDDED: Record<string, string> = {\n" + map.join("\n") + "\n};\n";
writeFileSync(join(root, "src", "assets.ts"), out);
console.log(`embedded ${embeddable.length} assets`);
console.log("bundled ai-eng-chain.ts (in-process plugin hosts)");
