// Generator for src/assets.ts: embeds every skills/ and templates/ file into the
// binary as Bun file imports. The binary IS the payload (blueprint 07). Run:
//   bun scripts/gen-assets.ts
// Also bundles src/chain for in-process plugin hosts (P0-2, 2026-09-01): the
// OMP/OpenCode plugin templates import ./ai-eng-chain.ts, which must be a
// self-contained module — not a re-export of src/ (its relative imports die in
// a foreign repo) and not a placeholder comment (the plugin never loaded).
import { readdirSync, writeFileSync, mkdirSync, appendFileSync, readFileSync } from "node:fs";
import { join, relative, dirname } from "node:path";

const root = join(import.meta.dir, "..");
const files: string[] = [];
function walk(dir: string): void {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) walk(full);
    else files.push(full);
  }
}

// ── the chain bundle FIRST: it must exist before the walk embeds it ──
// src/chain + a host-safe chain() wrapper, one self-contained file under
// skills/.chain-bundle/ (P0-2: the OMP/OpenCode plugin imports it as a module;
// a placeholder comment meant the plugin never loaded).
const { execSync } = await import("node:child_process");
const bundleDir = join(root, "skills", ".chain-bundle");
mkdirSync(bundleDir, { recursive: true });
execSync(`bun build scripts/chain-entry.ts --target=bun --format=esm --outfile=${JSON.stringify(join(bundleDir, "ai-eng-chain.ts"))}`, {
  cwd: root,
  stdio: "inherit",
});
// The bundle is loaded as a FILE string (with { type: "file" }) so the binary can
// plant it in foreign repos; tsc must type that import as `string`. A default
// export (the bundle's own id) lets tsc type the default import as a string
// without resolving the real module, and never affects plugins, which import the
// named `chain`/`runChain` exports.
appendFileSync(join(bundleDir, "ai-eng-chain.ts"), '\nexport default "ai-eng-chain";\n');

walk(join(root, "skills"));
walk(join(root, "templates"));
// .json stays embeddable (P0-3): ai-security's report-schema.json is read at
// runtime by validate-findings.cjs; excluding it shipped a broken validator.
// .ts/.tsx stay out EXCEPT the chain bundle itself and fixture data: a fixture
// repo is the SUBJECT an eval measures, never host code the binary executes —
// dropping it shipped an eval pack whose answer key cites files that were never
// materialized (measured 2026-09-10: example-node-web cites 4 of them).
//
// A fixture .ts/.tsx cannot be imported as an asset directly: tsc resolves it as a
// real module and refuses (no default export; .tsx without --jsx). The payload key
// stays the fixture's real path and the import points at a generated .txt copy —
// same bytes, an extension no resolver claims. Regenerated every build, so the copy
// cannot drift. The copies live OUTSIDE skills/ and templates/, so they are payload
// refs, never payload of their own.
const chainPrefix = bundleDir + "/";
const isFixtureData = (f: string): boolean => f.includes("/fixtures/");
const copyDir = join(root, "scripts", ".embed");
const entries: Array<{ key: string; source: string }> = [];
for (const file of files) {
  if (file.endsWith(".DS_Store")) continue;
  const key = relative(root, file);
  if (file.startsWith(chainPrefix)) {
    if (file.endsWith(".ts")) entries.push({ key, source: file });
    continue;
  }
  if (isFixtureData(file) && /\.tsx?$/.test(file)) {
    const copy = join(copyDir, `${relative(join(root, "skills"), file)}.txt`);
    mkdirSync(dirname(copy), { recursive: true });
    writeFileSync(copy, readFileSync(file));
    entries.push({ key, source: copy });
    continue;
  }
  if (/\.tsx?$/.test(file)) continue;
  entries.push({ key, source: file });
}

let out = "// GENERATED by scripts/gen-assets.ts - do not edit. The binary IS the payload (blueprint 07):\n// every skill and template travels inside it. Regenerate with: bun scripts/gen-assets.ts\n\n";

const lines: string[] = [];
const map: string[] = [];
for (const { key, source } of entries) {
  const ident = "a" + key.replace(/[^a-zA-Z0-9]/g, "_");
  lines.push(`import ${ident} from "../${relative(root, source)}" with { type: "file" };`);
  // Bun's `with { type: "file" }` returns the file TEXT, but tsc can't model that
  // for extensions that resolve as real modules (`.json` via resolveJsonModule,
  // the generated `.ts` chain bundle) and types the import as the module object.
  // The value is a string at runtime — this cast states the truth, it doesn't
  // suppress a check.
  map.push(`  "../${key}": ${ident} as unknown as string,`);
}
out += lines.join("\n") + "\n\nexport const EMBEDDED: Record<string, string> = {\n" + map.join("\n") + "\n};\n";
writeFileSync(join(root, "src", "assets.ts"), out);
console.log(`embedded ${entries.length} assets`);
console.log("bundled ai-eng-chain.ts (in-process plugin hosts)");
