// GENERATED by scripts/gen-assets.ts - do not edit. The binary IS the payload (blueprint 07):
// every skill and template travels inside it. Regenerate with: bun scripts/gen-assets.ts

import askills_ai_verify_evals_README_md from "../skills/ai-verify/evals/README.md" with { type: "file" };
import askills_ai_verify_evals_scripts_plant_py from "../skills/ai-verify/evals/scripts/plant.py" with { type: "file" };
import askills_ai_verify_evals_scripts_score_py from "../skills/ai-verify/evals/scripts/score.py" with { type: "file" };
import askills_ai_verify_evals_bug_catalog_md from "../skills/ai-verify/evals/bug-catalog.md" with { type: "file" };
import askills_ai_verify_tiers_3_chain_build_check_SKILL_md from "../skills/ai-verify/tiers/3-chain/build-check/SKILL.md" with { type: "file" };
import askills_ai_verify_tiers_3_chain_perf_audit_SKILL_md from "../skills/ai-verify/tiers/3-chain/perf-audit/SKILL.md" with { type: "file" };
import askills_ai_verify_tiers_3_chain_design_check_SKILL_md from "../skills/ai-verify/tiers/3-chain/design-check/SKILL.md" with { type: "file" };
import askills_ai_verify_tiers_3_chain_code_audit_SKILL_md from "../skills/ai-verify/tiers/3-chain/code-audit/SKILL.md" with { type: "file" };
import askills_ai_verify_tiers_3_chain__support_review_CONVENTIONS_md from "../skills/ai-verify/tiers/3-chain/_support/review/CONVENTIONS.md" with { type: "file" };
import askills_ai_verify_tiers_3_chain_full_review_SKILL_md from "../skills/ai-verify/tiers/3-chain/full-review/SKILL.md" with { type: "file" };
import askills_ai_verify_tiers_3_chain_review_router_SKILL_md from "../skills/ai-verify/tiers/3-chain/review-router/SKILL.md" with { type: "file" };
import askills_ai_verify_tiers_3_chain_security_audit_SKILL_md from "../skills/ai-verify/tiers/3-chain/security-audit/SKILL.md" with { type: "file" };
import askills_ai_verify_tiers_3_chain_a11y_audit_SKILL_md from "../skills/ai-verify/tiers/3-chain/a11y-audit/SKILL.md" with { type: "file" };
import askills_ai_verify_tiers_1_standalone_spec_extract_SKILL_md from "../skills/ai-verify/tiers/1-standalone/spec-extract/SKILL.md" with { type: "file" };
import askills_ai_verify_tiers_1_standalone_verify_feature_SKILL_md from "../skills/ai-verify/tiers/1-standalone/verify-feature/SKILL.md" with { type: "file" };
import askills_ai_verify_tiers_2_embedded_feature_verify_references_puppeteer_patterns_md from "../skills/ai-verify/tiers/2-embedded/feature-verify/references/puppeteer-patterns.md" with { type: "file" };
import askills_ai_verify_tiers_2_embedded_feature_verify_references_harness_md from "../skills/ai-verify/tiers/2-embedded/feature-verify/references/harness.md" with { type: "file" };
import askills_ai_verify_tiers_2_embedded_feature_verify_scripts_setup_harness_sh from "../skills/ai-verify/tiers/2-embedded/feature-verify/scripts/setup_harness.sh" with { type: "file" };
import askills_ai_verify_tiers_2_embedded_feature_verify_scripts_blast_radius_py from "../skills/ai-verify/tiers/2-embedded/feature-verify/scripts/blast_radius.py" with { type: "file" };
import askills_ai_verify_tiers_2_embedded_feature_verify_SKILL_md from "../skills/ai-verify/tiers/2-embedded/feature-verify/SKILL.md" with { type: "file" };
import askills_ai_verify_tiers_2_embedded_second_opinion_scripts_second_opinion_sh from "../skills/ai-verify/tiers/2-embedded/second-opinion/scripts/second-opinion.sh" with { type: "file" };
import askills_ai_verify_tiers_2_embedded_second_opinion_SKILL_md from "../skills/ai-verify/tiers/2-embedded/second-opinion/SKILL.md" with { type: "file" };
import askills_ai_verify_SKILL_md from "../skills/ai-verify/SKILL.md" with { type: "file" };
import askills_ai_verify_VERIFICATION_SETUP_GUIDE_md from "../skills/ai-verify/VERIFICATION-SETUP-GUIDE.md" with { type: "file" };
import askills_ai_security_references_AI_AND_LLM_md from "../skills/ai-security/references/AI-AND-LLM.md" with { type: "file" };
import askills_ai_security_references_RECONNAISSANCE_md from "../skills/ai-security/references/RECONNAISSANCE.md" with { type: "file" };
import askills_ai_security_references_MEMORY_SAFETY_AND_BINARY_md from "../skills/ai-security/references/MEMORY-SAFETY-AND-BINARY.md" with { type: "file" };
import askills_ai_security_references_validate_findings_cjs from "../skills/ai-security/references/validate-findings.cjs" with { type: "file" };
import askills_ai_security_references_WEB_PROTOCOL_AND_AUTH_md from "../skills/ai-security/references/WEB-PROTOCOL-AND-AUTH.md" with { type: "file" };
import askills_ai_security_references_ATTACK_CLASSES_md from "../skills/ai-security/references/ATTACK-CLASSES.md" with { type: "file" };
import askills_ai_security_references_CLIENT_SIDE_md from "../skills/ai-security/references/CLIENT-SIDE.md" with { type: "file" };
import askills_ai_security_references_VALIDATION_AND_REPORTING_md from "../skills/ai-security/references/VALIDATION-AND-REPORTING.md" with { type: "file" };
import askills_ai_security_references_HUNTING_md from "../skills/ai-security/references/HUNTING.md" with { type: "file" };
import askills_ai_security_SKILL_md from "../skills/ai-security/SKILL.md" with { type: "file" };
import askills_ai_architect_references_arxiv_prior_art_md from "../skills/ai-architect/references/arxiv-prior-art.md" with { type: "file" };
import askills_ai_architect_agents_openai_yaml from "../skills/ai-architect/agents/openai.yaml" with { type: "file" };
import askills_ai_architect_SKILL_md from "../skills/ai-architect/SKILL.md" with { type: "file" };
import askills_ai_brainstorm_references_spec_document_reviewer_prompt_md from "../skills/ai-brainstorm/references/spec-document-reviewer-prompt.md" with { type: "file" };
import askills_ai_brainstorm_SKILL_md from "../skills/ai-brainstorm/SKILL.md" with { type: "file" };
import askills_ai_agents_md_SKILL_md from "../skills/ai-agents-md/SKILL.md" with { type: "file" };
import askills_ai_research_SKILL_md from "../skills/ai-research/SKILL.md" with { type: "file" };
import askills_ai_design_references_conflicts_md from "../skills/ai-design/references/conflicts.md" with { type: "file" };
import askills_ai_design_references_plans_md from "../skills/ai-design/references/plans.md" with { type: "file" };
import askills_ai_design_references_skill_purposes_md from "../skills/ai-design/references/skill-purposes.md" with { type: "file" };
import askills_ai_design_references_routing_table_md from "../skills/ai-design/references/routing-table.md" with { type: "file" };
import askills_ai_design_SKILL_md from "../skills/ai-design/SKILL.md" with { type: "file" };
import askills_ai_writing_behavior_references_agent_behavior_specification_md from "../skills/ai-writing-behavior/references/agent-behavior-specification.md" with { type: "file" };
import askills_ai_writing_behavior_references_calibrating_with_trajectories_md from "../skills/ai-writing-behavior/references/calibrating-with-trajectories.md" with { type: "file" };
import askills_ai_writing_behavior_references_deciding_what_to_save_md from "../skills/ai-writing-behavior/references/deciding-what-to-save.md" with { type: "file" };
import askills_ai_writing_behavior_SKILL_md from "../skills/ai-writing-behavior/SKILL.md" with { type: "file" };
import askills_ai_explore_SKILL_md from "../skills/ai-explore/SKILL.md" with { type: "file" };
import askills_ai_issue_report_SKILL_md from "../skills/ai-issue-report/SKILL.md" with { type: "file" };
import askills_ai_goal_SKILL_md from "../skills/ai-goal/SKILL.md" with { type: "file" };
import askills_ai_goal_goal_writer_SKILL_md from "../skills/ai-goal/goal-writer/SKILL.md" with { type: "file" };
import askills_ai_goal_new_feature_SKILL_md from "../skills/ai-goal/new-feature/SKILL.md" with { type: "file" };
import askills_ai_goal_feature_batch_SKILL_md from "../skills/ai-goal/feature-batch/SKILL.md" with { type: "file" };
import askills_ai_debug_SKILL_md from "../skills/ai-debug/SKILL.md" with { type: "file" };
import askills_ai_visual_recap_references_connection_md from "../skills/ai-visual-recap/references/connection.md" with { type: "file" };
import askills_ai_visual_recap_references_local_files_md from "../skills/ai-visual-recap/references/local-files.md" with { type: "file" };
import askills_ai_visual_recap_references_wireframe_md from "../skills/ai-visual-recap/references/wireframe.md" with { type: "file" };
import askills_ai_visual_recap_SKILL_md from "../skills/ai-visual-recap/SKILL.md" with { type: "file" };
import askills_ai_write_references_documentation_writer_md from "../skills/ai-write/references/documentation-writer.md" with { type: "file" };
import askills_ai_write_SKILL_md from "../skills/ai-write/SKILL.md" with { type: "file" };
import askills_ai_proof_references_method_md from "../skills/ai-proof/references/method.md" with { type: "file" };
import askills_ai_proof_references_orchestration_md from "../skills/ai-proof/references/orchestration.md" with { type: "file" };
import askills_ai_proof_references_token_economy_md from "../skills/ai-proof/references/token-economy.md" with { type: "file" };
import askills_ai_proof_references_gates_md from "../skills/ai-proof/references/gates.md" with { type: "file" };
import askills_ai_proof_scripts_stop_hook_mjs from "../skills/ai-proof/scripts/stop-hook.mjs" with { type: "file" };
import askills_ai_proof_scripts_install_hooks_mjs from "../skills/ai-proof/scripts/install-hooks.mjs" with { type: "file" };
import askills_ai_proof_scripts_gate_check_mjs from "../skills/ai-proof/scripts/gate-check.mjs" with { type: "file" };
import askills_ai_proof_SKILL_md from "../skills/ai-proof/SKILL.md" with { type: "file" };
import askills_ai_proof_templates_gates_node_md from "../skills/ai-proof/templates/gates-node.md" with { type: "file" };
import askills_ai_proof_templates_PLAN_md from "../skills/ai-proof/templates/PLAN.md" with { type: "file" };
import askills_ai_proof_templates_gates_leaf_md from "../skills/ai-proof/templates/gates-leaf.md" with { type: "file" };
import askills_ai_design_audit_references_fixes_md from "../skills/ai-design-audit/references/fixes.md" with { type: "file" };
import askills_ai_design_audit_references_reading_md from "../skills/ai-design-audit/references/reading.md" with { type: "file" };
import askills_ai_design_audit_agents_openai_yaml from "../skills/ai-design-audit/agents/openai.yaml" with { type: "file" };
import askills_ai_design_audit_scripts_audit_mjs from "../skills/ai-design-audit/scripts/audit.mjs" with { type: "file" };
import askills_ai_design_audit_SKILL_md from "../skills/ai-design-audit/SKILL.md" with { type: "file" };
import askills_ai_note_SKILL_md from "../skills/ai-note/SKILL.md" with { type: "file" };
import askills_ai_read_docs_SKILL_md from "../skills/ai-read-docs/SKILL.md" with { type: "file" };
import askills_ai_rtk_references_commands_md from "../skills/ai-rtk/references/commands.md" with { type: "file" };
import askills_ai_rtk_SKILL_md from "../skills/ai-rtk/SKILL.md" with { type: "file" };
import askills_ai_plan_agents_openai_yaml from "../skills/ai-plan/agents/openai.yaml" with { type: "file" };
import askills_ai_plan_SKILL_md from "../skills/ai-plan/SKILL.md" with { type: "file" };
import askills_ai_plan_commands_prototype_md from "../skills/ai-plan/commands/prototype.md" with { type: "file" };
import askills_ai_plan_commands_to_bar_md from "../skills/ai-plan/commands/to-bar.md" with { type: "file" };
import askills_ai_plan_commands_grill_md from "../skills/ai-plan/commands/grill.md" with { type: "file" };
import atemplates_overrides_toml_tpl from "../templates/overrides.toml.tpl" with { type: "file" };
import atemplates_plan_html_tpl from "../templates/plan.html.tpl" with { type: "file" };
import atemplates_config_toml_tpl from "../templates/config.toml.tpl" with { type: "file" };
import atemplates_git_pre_push_tpl from "../templates/git-pre-push.tpl" with { type: "file" };
import atemplates_plugin_opencode_ts_tpl from "../templates/plugin.opencode.ts.tpl" with { type: "file" };
import atemplates_AGENTS_md_tpl from "../templates/AGENTS.md.tpl" with { type: "file" };
import atemplates_git_commit_msg_tpl from "../templates/git-commit-msg.tpl" with { type: "file" };
import atemplates_git_pre_commit_tpl from "../templates/git-pre-commit.tpl" with { type: "file" };
import atemplates_spec_html_tpl from "../templates/spec.html.tpl" with { type: "file" };
import atemplates_plugin_omp_ts_tpl from "../templates/plugin.omp.ts.tpl" with { type: "file" };
import atemplates_settings_claude_json_tpl from "../templates/settings.claude.json.tpl" with { type: "file" };
import atemplates_ci_yml_tpl from "../templates/ci.yml.tpl" with { type: "file" };
import atemplates_DECISIONS_md_tpl from "../templates/DECISIONS.md.tpl" with { type: "file" };
import atemplates_arch_rules_json_tpl from "../templates/arch.rules.json.tpl" with { type: "file" };

export const EMBEDDED: Record<string, string> = {
  "../skills/ai-verify/evals/README.md": askills_ai_verify_evals_README_md,
  "../skills/ai-verify/evals/scripts/plant.py": askills_ai_verify_evals_scripts_plant_py,
  "../skills/ai-verify/evals/scripts/score.py": askills_ai_verify_evals_scripts_score_py,
  "../skills/ai-verify/evals/bug-catalog.md": askills_ai_verify_evals_bug_catalog_md,
  "../skills/ai-verify/tiers/3-chain/build-check/SKILL.md": askills_ai_verify_tiers_3_chain_build_check_SKILL_md,
  "../skills/ai-verify/tiers/3-chain/perf-audit/SKILL.md": askills_ai_verify_tiers_3_chain_perf_audit_SKILL_md,
  "../skills/ai-verify/tiers/3-chain/design-check/SKILL.md": askills_ai_verify_tiers_3_chain_design_check_SKILL_md,
  "../skills/ai-verify/tiers/3-chain/code-audit/SKILL.md": askills_ai_verify_tiers_3_chain_code_audit_SKILL_md,
  "../skills/ai-verify/tiers/3-chain/_support/review/CONVENTIONS.md": askills_ai_verify_tiers_3_chain__support_review_CONVENTIONS_md,
  "../skills/ai-verify/tiers/3-chain/full-review/SKILL.md": askills_ai_verify_tiers_3_chain_full_review_SKILL_md,
  "../skills/ai-verify/tiers/3-chain/review-router/SKILL.md": askills_ai_verify_tiers_3_chain_review_router_SKILL_md,
  "../skills/ai-verify/tiers/3-chain/security-audit/SKILL.md": askills_ai_verify_tiers_3_chain_security_audit_SKILL_md,
  "../skills/ai-verify/tiers/3-chain/a11y-audit/SKILL.md": askills_ai_verify_tiers_3_chain_a11y_audit_SKILL_md,
  "../skills/ai-verify/tiers/1-standalone/spec-extract/SKILL.md": askills_ai_verify_tiers_1_standalone_spec_extract_SKILL_md,
  "../skills/ai-verify/tiers/1-standalone/verify-feature/SKILL.md": askills_ai_verify_tiers_1_standalone_verify_feature_SKILL_md,
  "../skills/ai-verify/tiers/2-embedded/feature-verify/references/puppeteer-patterns.md": askills_ai_verify_tiers_2_embedded_feature_verify_references_puppeteer_patterns_md,
  "../skills/ai-verify/tiers/2-embedded/feature-verify/references/harness.md": askills_ai_verify_tiers_2_embedded_feature_verify_references_harness_md,
  "../skills/ai-verify/tiers/2-embedded/feature-verify/scripts/setup_harness.sh": askills_ai_verify_tiers_2_embedded_feature_verify_scripts_setup_harness_sh,
  "../skills/ai-verify/tiers/2-embedded/feature-verify/scripts/blast_radius.py": askills_ai_verify_tiers_2_embedded_feature_verify_scripts_blast_radius_py,
  "../skills/ai-verify/tiers/2-embedded/feature-verify/SKILL.md": askills_ai_verify_tiers_2_embedded_feature_verify_SKILL_md,
  "../skills/ai-verify/tiers/2-embedded/second-opinion/scripts/second-opinion.sh": askills_ai_verify_tiers_2_embedded_second_opinion_scripts_second_opinion_sh,
  "../skills/ai-verify/tiers/2-embedded/second-opinion/SKILL.md": askills_ai_verify_tiers_2_embedded_second_opinion_SKILL_md,
  "../skills/ai-verify/SKILL.md": askills_ai_verify_SKILL_md,
  "../skills/ai-verify/VERIFICATION-SETUP-GUIDE.md": askills_ai_verify_VERIFICATION_SETUP_GUIDE_md,
  "../skills/ai-security/references/AI-AND-LLM.md": askills_ai_security_references_AI_AND_LLM_md,
  "../skills/ai-security/references/RECONNAISSANCE.md": askills_ai_security_references_RECONNAISSANCE_md,
  "../skills/ai-security/references/MEMORY-SAFETY-AND-BINARY.md": askills_ai_security_references_MEMORY_SAFETY_AND_BINARY_md,
  "../skills/ai-security/references/validate-findings.cjs": askills_ai_security_references_validate_findings_cjs,
  "../skills/ai-security/references/WEB-PROTOCOL-AND-AUTH.md": askills_ai_security_references_WEB_PROTOCOL_AND_AUTH_md,
  "../skills/ai-security/references/ATTACK-CLASSES.md": askills_ai_security_references_ATTACK_CLASSES_md,
  "../skills/ai-security/references/CLIENT-SIDE.md": askills_ai_security_references_CLIENT_SIDE_md,
  "../skills/ai-security/references/VALIDATION-AND-REPORTING.md": askills_ai_security_references_VALIDATION_AND_REPORTING_md,
  "../skills/ai-security/references/HUNTING.md": askills_ai_security_references_HUNTING_md,
  "../skills/ai-security/SKILL.md": askills_ai_security_SKILL_md,
  "../skills/ai-architect/references/arxiv-prior-art.md": askills_ai_architect_references_arxiv_prior_art_md,
  "../skills/ai-architect/agents/openai.yaml": askills_ai_architect_agents_openai_yaml,
  "../skills/ai-architect/SKILL.md": askills_ai_architect_SKILL_md,
  "../skills/ai-brainstorm/references/spec-document-reviewer-prompt.md": askills_ai_brainstorm_references_spec_document_reviewer_prompt_md,
  "../skills/ai-brainstorm/SKILL.md": askills_ai_brainstorm_SKILL_md,
  "../skills/ai-agents-md/SKILL.md": askills_ai_agents_md_SKILL_md,
  "../skills/ai-research/SKILL.md": askills_ai_research_SKILL_md,
  "../skills/ai-design/references/conflicts.md": askills_ai_design_references_conflicts_md,
  "../skills/ai-design/references/plans.md": askills_ai_design_references_plans_md,
  "../skills/ai-design/references/skill-purposes.md": askills_ai_design_references_skill_purposes_md,
  "../skills/ai-design/references/routing-table.md": askills_ai_design_references_routing_table_md,
  "../skills/ai-design/SKILL.md": askills_ai_design_SKILL_md,
  "../skills/ai-writing-behavior/references/agent-behavior-specification.md": askills_ai_writing_behavior_references_agent_behavior_specification_md,
  "../skills/ai-writing-behavior/references/calibrating-with-trajectories.md": askills_ai_writing_behavior_references_calibrating_with_trajectories_md,
  "../skills/ai-writing-behavior/references/deciding-what-to-save.md": askills_ai_writing_behavior_references_deciding_what_to_save_md,
  "../skills/ai-writing-behavior/SKILL.md": askills_ai_writing_behavior_SKILL_md,
  "../skills/ai-explore/SKILL.md": askills_ai_explore_SKILL_md,
  "../skills/ai-issue-report/SKILL.md": askills_ai_issue_report_SKILL_md,
  "../skills/ai-goal/SKILL.md": askills_ai_goal_SKILL_md,
  "../skills/ai-goal/goal-writer/SKILL.md": askills_ai_goal_goal_writer_SKILL_md,
  "../skills/ai-goal/new-feature/SKILL.md": askills_ai_goal_new_feature_SKILL_md,
  "../skills/ai-goal/feature-batch/SKILL.md": askills_ai_goal_feature_batch_SKILL_md,
  "../skills/ai-debug/SKILL.md": askills_ai_debug_SKILL_md,
  "../skills/ai-visual-recap/references/connection.md": askills_ai_visual_recap_references_connection_md,
  "../skills/ai-visual-recap/references/local-files.md": askills_ai_visual_recap_references_local_files_md,
  "../skills/ai-visual-recap/references/wireframe.md": askills_ai_visual_recap_references_wireframe_md,
  "../skills/ai-visual-recap/SKILL.md": askills_ai_visual_recap_SKILL_md,
  "../skills/ai-write/references/documentation-writer.md": askills_ai_write_references_documentation_writer_md,
  "../skills/ai-write/SKILL.md": askills_ai_write_SKILL_md,
  "../skills/ai-proof/references/method.md": askills_ai_proof_references_method_md,
  "../skills/ai-proof/references/orchestration.md": askills_ai_proof_references_orchestration_md,
  "../skills/ai-proof/references/token-economy.md": askills_ai_proof_references_token_economy_md,
  "../skills/ai-proof/references/gates.md": askills_ai_proof_references_gates_md,
  "../skills/ai-proof/scripts/stop-hook.mjs": askills_ai_proof_scripts_stop_hook_mjs,
  "../skills/ai-proof/scripts/install-hooks.mjs": askills_ai_proof_scripts_install_hooks_mjs,
  "../skills/ai-proof/scripts/gate-check.mjs": askills_ai_proof_scripts_gate_check_mjs,
  "../skills/ai-proof/SKILL.md": askills_ai_proof_SKILL_md,
  "../skills/ai-proof/templates/gates-node.md": askills_ai_proof_templates_gates_node_md,
  "../skills/ai-proof/templates/PLAN.md": askills_ai_proof_templates_PLAN_md,
  "../skills/ai-proof/templates/gates-leaf.md": askills_ai_proof_templates_gates_leaf_md,
  "../skills/ai-design-audit/references/fixes.md": askills_ai_design_audit_references_fixes_md,
  "../skills/ai-design-audit/references/reading.md": askills_ai_design_audit_references_reading_md,
  "../skills/ai-design-audit/agents/openai.yaml": askills_ai_design_audit_agents_openai_yaml,
  "../skills/ai-design-audit/scripts/audit.mjs": askills_ai_design_audit_scripts_audit_mjs,
  "../skills/ai-design-audit/SKILL.md": askills_ai_design_audit_SKILL_md,
  "../skills/ai-note/SKILL.md": askills_ai_note_SKILL_md,
  "../skills/ai-read-docs/SKILL.md": askills_ai_read_docs_SKILL_md,
  "../skills/ai-rtk/references/commands.md": askills_ai_rtk_references_commands_md,
  "../skills/ai-rtk/SKILL.md": askills_ai_rtk_SKILL_md,
  "../skills/ai-plan/agents/openai.yaml": askills_ai_plan_agents_openai_yaml,
  "../skills/ai-plan/SKILL.md": askills_ai_plan_SKILL_md,
  "../skills/ai-plan/commands/prototype.md": askills_ai_plan_commands_prototype_md,
  "../skills/ai-plan/commands/to-bar.md": askills_ai_plan_commands_to_bar_md,
  "../skills/ai-plan/commands/grill.md": askills_ai_plan_commands_grill_md,
  "../templates/overrides.toml.tpl": atemplates_overrides_toml_tpl,
  "../templates/plan.html.tpl": atemplates_plan_html_tpl,
  "../templates/config.toml.tpl": atemplates_config_toml_tpl,
  "../templates/git-pre-push.tpl": atemplates_git_pre_push_tpl,
  "../templates/plugin.opencode.ts.tpl": atemplates_plugin_opencode_ts_tpl,
  "../templates/AGENTS.md.tpl": atemplates_AGENTS_md_tpl,
  "../templates/git-commit-msg.tpl": atemplates_git_commit_msg_tpl,
  "../templates/git-pre-commit.tpl": atemplates_git_pre_commit_tpl,
  "../templates/spec.html.tpl": atemplates_spec_html_tpl,
  "../templates/plugin.omp.ts.tpl": atemplates_plugin_omp_ts_tpl,
  "../templates/settings.claude.json.tpl": atemplates_settings_claude_json_tpl,
  "../templates/ci.yml.tpl": atemplates_ci_yml_tpl,
  "../templates/DECISIONS.md.tpl": atemplates_DECISIONS_md_tpl,
  "../templates/arch.rules.json.tpl": atemplates_arch_rules_json_tpl,
};
