// GENERATED by scripts/gen-assets.ts - do not edit. The binary IS the payload (blueprint 07):
// every skill and template travels inside it. Regenerate with: bun scripts/gen-assets.ts

import askills_ai_verify_evals_README_md from "../skills/ai-verify/evals/README.md" with { type: "file" };
import askills_ai_verify_evals_packs_example_node_web_answer_key_json from "../skills/ai-verify/evals/packs/example-node-web/answer-key.json" with { type: "file" };
import askills_ai_verify_evals_scripts_score_ts from "../scripts/.embed/ai-verify/evals/scripts/score.ts.txt" with { type: "file" };
import askills_ai_verify_evals_scripts_apply_pack_ts from "../scripts/.embed/ai-verify/evals/scripts/apply-pack.ts.txt" with { type: "file" };
import askills_ai_verify_evals_bug_catalog_md from "../skills/ai-verify/evals/bug-catalog.md" with { type: "file" };
import askills_ai_verify_evals_fixtures_node_web_package_json from "../skills/ai-verify/evals/fixtures/node-web/package.json" with { type: "file" };
import askills_ai_verify_evals_fixtures_node_web_src_ui_OrderList_tsx from "../scripts/.embed/ai-verify/evals/fixtures/node-web/src/ui/OrderList.tsx.txt" with { type: "file" };
import askills_ai_verify_evals_fixtures_node_web_src_auth_session_ts from "../scripts/.embed/ai-verify/evals/fixtures/node-web/src/auth/session.ts.txt" with { type: "file" };
import askills_ai_verify_evals_fixtures_node_web_src_db_queries_ts from "../scripts/.embed/ai-verify/evals/fixtures/node-web/src/db/queries.ts.txt" with { type: "file" };
import askills_ai_verify_evals_fixtures_node_web_src_api_orders_ts from "../scripts/.embed/ai-verify/evals/fixtures/node-web/src/api/orders.ts.txt" with { type: "file" };
import askills_ai_verify_tiers_3_chain_build_check_SKILL_md from "../skills/ai-verify/tiers/3-chain/build-check/SKILL.md" with { type: "file" };
import askills_ai_verify_tiers_3_chain_perf_audit_SKILL_md from "../skills/ai-verify/tiers/3-chain/perf-audit/SKILL.md" with { type: "file" };
import askills_ai_verify_tiers_3_chain_design_check_SKILL_md from "../skills/ai-verify/tiers/3-chain/design-check/SKILL.md" with { type: "file" };
import askills_ai_verify_tiers_3_chain_code_audit_SKILL_md from "../skills/ai-verify/tiers/3-chain/code-audit/SKILL.md" with { type: "file" };
import askills_ai_verify_tiers_3_chain__support_review_CONVENTIONS_md from "../skills/ai-verify/tiers/3-chain/_support/review/CONVENTIONS.md" with { type: "file" };
import askills_ai_verify_tiers_3_chain_full_review_SKILL_md from "../skills/ai-verify/tiers/3-chain/full-review/SKILL.md" with { type: "file" };
import askills_ai_verify_tiers_3_chain_review_router_SKILL_md from "../skills/ai-verify/tiers/3-chain/review-router/SKILL.md" with { type: "file" };
import askills_ai_verify_tiers_3_chain_security_audit_SKILL_md from "../skills/ai-verify/tiers/3-chain/security-audit/SKILL.md" with { type: "file" };
import askills_ai_verify_tiers_3_chain_a11y_audit_SKILL_md from "../skills/ai-verify/tiers/3-chain/a11y-audit/SKILL.md" with { type: "file" };
import askills_ai_verify_tiers_1_standalone_spec_extract_SKILL_md from "../skills/ai-verify/tiers/1-standalone/spec-extract/SKILL.md" with { type: "file" };
import askills_ai_verify_tiers_1_standalone_verify_feature_SKILL_md from "../skills/ai-verify/tiers/1-standalone/verify-feature/SKILL.md" with { type: "file" };
import askills_ai_verify_tiers_2_embedded_feature_verify_references_puppeteer_patterns_md from "../skills/ai-verify/tiers/2-embedded/feature-verify/references/puppeteer-patterns.md" with { type: "file" };
import askills_ai_verify_tiers_2_embedded_feature_verify_references_harness_md from "../skills/ai-verify/tiers/2-embedded/feature-verify/references/harness.md" with { type: "file" };
import askills_ai_verify_tiers_2_embedded_feature_verify_scripts_blast_radius_ts from "../scripts/.embed/ai-verify/tiers/2-embedded/feature-verify/scripts/blast_radius.ts.txt" with { type: "file" };
import askills_ai_verify_tiers_2_embedded_feature_verify_scripts_setup_harness_sh from "../skills/ai-verify/tiers/2-embedded/feature-verify/scripts/setup_harness.sh" with { type: "file" };
import askills_ai_verify_tiers_2_embedded_feature_verify_SKILL_md from "../skills/ai-verify/tiers/2-embedded/feature-verify/SKILL.md" with { type: "file" };
import askills_ai_verify_tiers_2_embedded_second_opinion_scripts_second_opinion_sh from "../skills/ai-verify/tiers/2-embedded/second-opinion/scripts/second-opinion.sh" with { type: "file" };
import askills_ai_verify_tiers_2_embedded_second_opinion_SKILL_md from "../skills/ai-verify/tiers/2-embedded/second-opinion/SKILL.md" with { type: "file" };
import askills_ai_verify_SKILL_md from "../skills/ai-verify/SKILL.md" with { type: "file" };
import askills_ai_verify_VERIFICATION_SETUP_GUIDE_md from "../skills/ai-verify/VERIFICATION-SETUP-GUIDE.md" with { type: "file" };
import askills_ai_security_references_AI_AND_LLM_md from "../skills/ai-security/references/AI-AND-LLM.md" with { type: "file" };
import askills_ai_security_references_RECONNAISSANCE_md from "../skills/ai-security/references/RECONNAISSANCE.md" with { type: "file" };
import askills_ai_security_references_MEMORY_SAFETY_AND_BINARY_md from "../skills/ai-security/references/MEMORY-SAFETY-AND-BINARY.md" with { type: "file" };
import askills_ai_security_references_validate_findings_cjs from "../skills/ai-security/references/validate-findings.cjs" with { type: "file" };
import askills_ai_security_references_report_schema_json from "../skills/ai-security/references/report-schema.json" with { type: "file" };
import askills_ai_security_references_WEB_PROTOCOL_AND_AUTH_md from "../skills/ai-security/references/WEB-PROTOCOL-AND-AUTH.md" with { type: "file" };
import askills_ai_security_references_ATTACK_CLASSES_md from "../skills/ai-security/references/ATTACK-CLASSES.md" with { type: "file" };
import askills_ai_security_references_CLIENT_SIDE_md from "../skills/ai-security/references/CLIENT-SIDE.md" with { type: "file" };
import askills_ai_security_references_VALIDATION_AND_REPORTING_md from "../skills/ai-security/references/VALIDATION-AND-REPORTING.md" with { type: "file" };
import askills_ai_security_references_HUNTING_md from "../skills/ai-security/references/HUNTING.md" with { type: "file" };
import askills_ai_security_SKILL_md from "../skills/ai-security/SKILL.md" with { type: "file" };
import askills_ai_architect_references_arxiv_prior_art_md from "../skills/ai-architect/references/arxiv-prior-art.md" with { type: "file" };
import askills_ai_architect_agents_openai_yaml from "../skills/ai-architect/agents/openai.yaml" with { type: "file" };
import askills_ai_architect_SKILL_md from "../skills/ai-architect/SKILL.md" with { type: "file" };
import askills_ai_brainstorm_references_spec_document_reviewer_prompt_md from "../skills/ai-brainstorm/references/spec-document-reviewer-prompt.md" with { type: "file" };
import askills_ai_brainstorm_references_artifact_design_md from "../skills/ai-brainstorm/references/artifact-design.md" with { type: "file" };
import askills_ai_brainstorm_SKILL_md from "../skills/ai-brainstorm/SKILL.md" with { type: "file" };
import askills_ai_agents_md_SKILL_md from "../skills/ai-agents-md/SKILL.md" with { type: "file" };
import askills_ai_codegraph_SKILL_md from "../skills/ai-codegraph/SKILL.md" with { type: "file" };
import askills_ai_research_SKILL_md from "../skills/ai-research/SKILL.md" with { type: "file" };
import askills_ai_adversarial_loop_SKILL_md from "../skills/ai-adversarial-loop/SKILL.md" with { type: "file" };
import askills_ai_writing_behavior_references_agent_behavior_specification_md from "../skills/ai-writing-behavior/references/agent-behavior-specification.md" with { type: "file" };
import askills_ai_writing_behavior_references_calibrating_with_trajectories_md from "../skills/ai-writing-behavior/references/calibrating-with-trajectories.md" with { type: "file" };
import askills_ai_writing_behavior_references_deciding_what_to_save_md from "../skills/ai-writing-behavior/references/deciding-what-to-save.md" with { type: "file" };
import askills_ai_writing_behavior_SKILL_md from "../skills/ai-writing-behavior/SKILL.md" with { type: "file" };
import askills_ai_pr_loop_fix_SKILL_md from "../skills/ai-pr-loop-fix/SKILL.md" with { type: "file" };
import askills_ai_explore_SKILL_md from "../skills/ai-explore/SKILL.md" with { type: "file" };
import askills_ai_issue_report_SKILL_md from "../skills/ai-issue-report/SKILL.md" with { type: "file" };
import askills_ai_orchestrator_SKILL_md from "../skills/ai-orchestrator/SKILL.md" with { type: "file" };
import askills_ai_debug_SKILL_md from "../skills/ai-debug/SKILL.md" with { type: "file" };
import askills_ai_design_md_planner_references_cli_md from "../skills/ai-design-md-planner/references/cli.md" with { type: "file" };
import askills_ai_design_md_planner_references_anti_slop_md from "../skills/ai-design-md-planner/references/anti-slop.md" with { type: "file" };
import askills_ai_design_md_planner_references_color_craft_md from "../skills/ai-design-md-planner/references/color-craft.md" with { type: "file" };
import askills_ai_design_md_planner_references_designmd_spec_md from "../skills/ai-design-md-planner/references/designmd-spec.md" with { type: "file" };
import askills_ai_design_md_planner_references_typography_md from "../skills/ai-design-md-planner/references/typography.md" with { type: "file" };
import askills_ai_design_md_planner_references_style_directions_md from "../skills/ai-design-md-planner/references/style-directions.md" with { type: "file" };
import askills_ai_design_md_planner_SKILL_md from "../skills/ai-design-md-planner/SKILL.md" with { type: "file" };
import askills_ai_design_md_planner_assets_DESIGN_example_md from "../skills/ai-design-md-planner/assets/DESIGN.example.md" with { type: "file" };
import askills_ai_design_md_planner_assets_DESIGN_template_md from "../skills/ai-design-md-planner/assets/DESIGN.template.md" with { type: "file" };
import askills_ai_visual_recap_references_connection_md from "../skills/ai-visual-recap/references/connection.md" with { type: "file" };
import askills_ai_visual_recap_references_local_files_md from "../skills/ai-visual-recap/references/local-files.md" with { type: "file" };
import askills_ai_visual_recap_references_wireframe_md from "../skills/ai-visual-recap/references/wireframe.md" with { type: "file" };
import askills_ai_visual_recap_SKILL_md from "../skills/ai-visual-recap/SKILL.md" with { type: "file" };
import askills_ai_visual_recap_assets_highlight_mjs from "../skills/ai-visual-recap/assets/highlight.mjs" with { type: "file" };
import askills_ai_test_planner_SKILL_md from "../skills/ai-test-planner/SKILL.md" with { type: "file" };
import askills_ai_write_references_security_md_writer_md from "../skills/ai-write/references/security-md-writer.md" with { type: "file" };
import askills_ai_write_references_voice_md from "../skills/ai-write/references/voice.md" with { type: "file" };
import askills_ai_write_references_readme_writer_md from "../skills/ai-write/references/readme-writer.md" with { type: "file" };
import askills_ai_write_references_contributing_writer_md from "../skills/ai-write/references/contributing-writer.md" with { type: "file" };
import askills_ai_write_references_documentation_writer_md from "../skills/ai-write/references/documentation-writer.md" with { type: "file" };
import askills_ai_write_SKILL_md from "../skills/ai-write/SKILL.md" with { type: "file" };
import askills_ai_config_to_project_SKILL_md from "../skills/ai-config-to-project/SKILL.md" with { type: "file" };
import askills_ai_code_review_SKILL_md from "../skills/ai-code-review/SKILL.md" with { type: "file" };
import askills_ai_review_ui_capture_cjs from "../skills/ai-review-ui/capture.cjs" with { type: "file" };
import askills_ai_review_ui_SKILL_md from "../skills/ai-review-ui/SKILL.md" with { type: "file" };
import askills_ai_note_SKILL_md from "../skills/ai-note/SKILL.md" with { type: "file" };
import askills_ai_read_docs_SKILL_md from "../skills/ai-read-docs/SKILL.md" with { type: "file" };
import askills__chain_bundle_ai_eng_chain_ts from "../skills/.chain-bundle/ai-eng-chain.ts" with { type: "file" };
import askills_ai_prototype_SKILL_md from "../skills/ai-prototype/SKILL.md" with { type: "file" };
import askills_ai_stress_test_references_tool_selection_md from "../skills/ai-stress-test/references/tool-selection.md" with { type: "file" };
import askills_ai_stress_test_references_safety_md from "../skills/ai-stress-test/references/safety.md" with { type: "file" };
import askills_ai_stress_test_SKILL_md from "../skills/ai-stress-test/SKILL.md" with { type: "file" };
import askills_ai_audit_code_SKILL_md from "../skills/ai-audit-code/SKILL.md" with { type: "file" };
import askills_ai_audit_docs_SKILL_md from "../skills/ai-audit-docs/SKILL.md" with { type: "file" };
import askills_ai_audit_design_references_fixes_md from "../skills/ai-audit-design/references/fixes.md" with { type: "file" };
import askills_ai_audit_design_references_reading_md from "../skills/ai-audit-design/references/reading.md" with { type: "file" };
import askills_ai_audit_design_references_accessibility_checklist_md from "../skills/ai-audit-design/references/accessibility-checklist.md" with { type: "file" };
import askills_ai_audit_design_agents_openai_yaml from "../skills/ai-audit-design/agents/openai.yaml" with { type: "file" };
import askills_ai_audit_design_scripts_audit_mjs from "../skills/ai-audit-design/scripts/audit.mjs" with { type: "file" };
import askills_ai_audit_design_SKILL_md from "../skills/ai-audit-design/SKILL.md" with { type: "file" };
import aagents_ui_visual_reviewer_md from "../agents/ui-visual-reviewer.md" with { type: "file" };
import aagents_adversarial_reviewer_md from "../agents/adversarial-reviewer.md" with { type: "file" };
import aagents_ui_behavior_reviewer_md from "../agents/ui-behavior-reviewer.md" with { type: "file" };
import aagents_checkpoint_planner_md from "../agents/checkpoint-planner.md" with { type: "file" };
import aagents_fixer_md from "../agents/fixer.md" with { type: "file" };
import atemplates_FILEMAP_md_tpl from "../templates/FILEMAP.md.tpl" with { type: "file" };
import atemplates_CHANGELOG_md_tpl from "../templates/CHANGELOG.md.tpl" with { type: "file" };
import atemplates_settings_copilot_json_tpl from "../templates/settings.copilot.json.tpl" with { type: "file" };
import atemplates_settings_codex_json_tpl from "../templates/settings.codex.json.tpl" with { type: "file" };
import atemplates_overrides_toml_tpl from "../templates/overrides.toml.tpl" with { type: "file" };
import atemplates_plan_html_tpl from "../templates/plan.html.tpl" with { type: "file" };
import atemplates_LEARNINGS_md_tpl from "../templates/LEARNINGS.md.tpl" with { type: "file" };
import atemplates_config_toml_tpl from "../templates/config.toml.tpl" with { type: "file" };
import atemplates_git_pre_push_tpl from "../templates/git-pre-push.tpl" with { type: "file" };
import atemplates_plugin_opencode_ts_tpl from "../templates/plugin.opencode.ts.tpl" with { type: "file" };
import atemplates_brainstorm_html_tpl from "../templates/brainstorm.html.tpl" with { type: "file" };
import atemplates_settings_copilot_cli_json_tpl from "../templates/settings.copilot.cli.json.tpl" with { type: "file" };
import atemplates_AGENTS_md_tpl from "../templates/AGENTS.md.tpl" with { type: "file" };
import atemplates_gitignore_tpl from "../templates/gitignore.tpl" with { type: "file" };
import atemplates_git_commit_msg_tpl from "../templates/git-commit-msg.tpl" with { type: "file" };
import atemplates_git_pre_commit_tpl from "../templates/git-pre-commit.tpl" with { type: "file" };
import atemplates_PRD_html_tpl from "../templates/PRD.html.tpl" with { type: "file" };
import atemplates_spec_html_tpl from "../templates/spec.html.tpl" with { type: "file" };
import atemplates_plugin_omp_ts_tpl from "../templates/plugin.omp.ts.tpl" with { type: "file" };
import atemplates_plugin_pi_ts_tpl from "../templates/plugin.pi.ts.tpl" with { type: "file" };
import atemplates_settings_claude_json_tpl from "../templates/settings.claude.json.tpl" with { type: "file" };
import atemplates_ci_yml_tpl from "../templates/ci.yml.tpl" with { type: "file" };
import atemplates_DECISIONS_md_tpl from "../templates/DECISIONS.md.tpl" with { type: "file" };
import atemplates_settings_cursor_json_tpl from "../templates/settings.cursor.json.tpl" with { type: "file" };
import atemplates_PERMISSIONS_md_tpl from "../templates/PERMISSIONS.md.tpl" with { type: "file" };
import atemplates_recap_html_tpl from "../templates/recap.html.tpl" with { type: "file" };
import atemplates_arch_rules_json_tpl from "../templates/arch.rules.json.tpl" with { type: "file" };
import atemplates_viewer_html_tpl from "../templates/viewer.html.tpl" with { type: "file" };
import ascripts_checkpoint_gate_py from "../scripts/checkpoint-gate.py" with { type: "file" };

export const EMBEDDED: Record<string, string> = {
  "../skills/ai-verify/evals/README.md": askills_ai_verify_evals_README_md as unknown as string,
  "../skills/ai-verify/evals/packs/example-node-web/answer-key.json": askills_ai_verify_evals_packs_example_node_web_answer_key_json as unknown as string,
  "../skills/ai-verify/evals/scripts/score.ts": askills_ai_verify_evals_scripts_score_ts as unknown as string,
  "../skills/ai-verify/evals/scripts/apply-pack.ts": askills_ai_verify_evals_scripts_apply_pack_ts as unknown as string,
  "../skills/ai-verify/evals/bug-catalog.md": askills_ai_verify_evals_bug_catalog_md as unknown as string,
  "../skills/ai-verify/evals/fixtures/node-web/package.json": askills_ai_verify_evals_fixtures_node_web_package_json as unknown as string,
  "../skills/ai-verify/evals/fixtures/node-web/src/ui/OrderList.tsx": askills_ai_verify_evals_fixtures_node_web_src_ui_OrderList_tsx as unknown as string,
  "../skills/ai-verify/evals/fixtures/node-web/src/auth/session.ts": askills_ai_verify_evals_fixtures_node_web_src_auth_session_ts as unknown as string,
  "../skills/ai-verify/evals/fixtures/node-web/src/db/queries.ts": askills_ai_verify_evals_fixtures_node_web_src_db_queries_ts as unknown as string,
  "../skills/ai-verify/evals/fixtures/node-web/src/api/orders.ts": askills_ai_verify_evals_fixtures_node_web_src_api_orders_ts as unknown as string,
  "../skills/ai-verify/tiers/3-chain/build-check/SKILL.md": askills_ai_verify_tiers_3_chain_build_check_SKILL_md as unknown as string,
  "../skills/ai-verify/tiers/3-chain/perf-audit/SKILL.md": askills_ai_verify_tiers_3_chain_perf_audit_SKILL_md as unknown as string,
  "../skills/ai-verify/tiers/3-chain/design-check/SKILL.md": askills_ai_verify_tiers_3_chain_design_check_SKILL_md as unknown as string,
  "../skills/ai-verify/tiers/3-chain/code-audit/SKILL.md": askills_ai_verify_tiers_3_chain_code_audit_SKILL_md as unknown as string,
  "../skills/ai-verify/tiers/3-chain/_support/review/CONVENTIONS.md": askills_ai_verify_tiers_3_chain__support_review_CONVENTIONS_md as unknown as string,
  "../skills/ai-verify/tiers/3-chain/full-review/SKILL.md": askills_ai_verify_tiers_3_chain_full_review_SKILL_md as unknown as string,
  "../skills/ai-verify/tiers/3-chain/review-router/SKILL.md": askills_ai_verify_tiers_3_chain_review_router_SKILL_md as unknown as string,
  "../skills/ai-verify/tiers/3-chain/security-audit/SKILL.md": askills_ai_verify_tiers_3_chain_security_audit_SKILL_md as unknown as string,
  "../skills/ai-verify/tiers/3-chain/a11y-audit/SKILL.md": askills_ai_verify_tiers_3_chain_a11y_audit_SKILL_md as unknown as string,
  "../skills/ai-verify/tiers/1-standalone/spec-extract/SKILL.md": askills_ai_verify_tiers_1_standalone_spec_extract_SKILL_md as unknown as string,
  "../skills/ai-verify/tiers/1-standalone/verify-feature/SKILL.md": askills_ai_verify_tiers_1_standalone_verify_feature_SKILL_md as unknown as string,
  "../skills/ai-verify/tiers/2-embedded/feature-verify/references/puppeteer-patterns.md": askills_ai_verify_tiers_2_embedded_feature_verify_references_puppeteer_patterns_md as unknown as string,
  "../skills/ai-verify/tiers/2-embedded/feature-verify/references/harness.md": askills_ai_verify_tiers_2_embedded_feature_verify_references_harness_md as unknown as string,
  "../skills/ai-verify/tiers/2-embedded/feature-verify/scripts/blast_radius.ts": askills_ai_verify_tiers_2_embedded_feature_verify_scripts_blast_radius_ts as unknown as string,
  "../skills/ai-verify/tiers/2-embedded/feature-verify/scripts/setup_harness.sh": askills_ai_verify_tiers_2_embedded_feature_verify_scripts_setup_harness_sh as unknown as string,
  "../skills/ai-verify/tiers/2-embedded/feature-verify/SKILL.md": askills_ai_verify_tiers_2_embedded_feature_verify_SKILL_md as unknown as string,
  "../skills/ai-verify/tiers/2-embedded/second-opinion/scripts/second-opinion.sh": askills_ai_verify_tiers_2_embedded_second_opinion_scripts_second_opinion_sh as unknown as string,
  "../skills/ai-verify/tiers/2-embedded/second-opinion/SKILL.md": askills_ai_verify_tiers_2_embedded_second_opinion_SKILL_md as unknown as string,
  "../skills/ai-verify/SKILL.md": askills_ai_verify_SKILL_md as unknown as string,
  "../skills/ai-verify/VERIFICATION-SETUP-GUIDE.md": askills_ai_verify_VERIFICATION_SETUP_GUIDE_md as unknown as string,
  "../skills/ai-security/references/AI-AND-LLM.md": askills_ai_security_references_AI_AND_LLM_md as unknown as string,
  "../skills/ai-security/references/RECONNAISSANCE.md": askills_ai_security_references_RECONNAISSANCE_md as unknown as string,
  "../skills/ai-security/references/MEMORY-SAFETY-AND-BINARY.md": askills_ai_security_references_MEMORY_SAFETY_AND_BINARY_md as unknown as string,
  "../skills/ai-security/references/validate-findings.cjs": askills_ai_security_references_validate_findings_cjs as unknown as string,
  "../skills/ai-security/references/report-schema.json": askills_ai_security_references_report_schema_json as unknown as string,
  "../skills/ai-security/references/WEB-PROTOCOL-AND-AUTH.md": askills_ai_security_references_WEB_PROTOCOL_AND_AUTH_md as unknown as string,
  "../skills/ai-security/references/ATTACK-CLASSES.md": askills_ai_security_references_ATTACK_CLASSES_md as unknown as string,
  "../skills/ai-security/references/CLIENT-SIDE.md": askills_ai_security_references_CLIENT_SIDE_md as unknown as string,
  "../skills/ai-security/references/VALIDATION-AND-REPORTING.md": askills_ai_security_references_VALIDATION_AND_REPORTING_md as unknown as string,
  "../skills/ai-security/references/HUNTING.md": askills_ai_security_references_HUNTING_md as unknown as string,
  "../skills/ai-security/SKILL.md": askills_ai_security_SKILL_md as unknown as string,
  "../skills/ai-architect/references/arxiv-prior-art.md": askills_ai_architect_references_arxiv_prior_art_md as unknown as string,
  "../skills/ai-architect/agents/openai.yaml": askills_ai_architect_agents_openai_yaml as unknown as string,
  "../skills/ai-architect/SKILL.md": askills_ai_architect_SKILL_md as unknown as string,
  "../skills/ai-brainstorm/references/spec-document-reviewer-prompt.md": askills_ai_brainstorm_references_spec_document_reviewer_prompt_md as unknown as string,
  "../skills/ai-brainstorm/references/artifact-design.md": askills_ai_brainstorm_references_artifact_design_md as unknown as string,
  "../skills/ai-brainstorm/SKILL.md": askills_ai_brainstorm_SKILL_md as unknown as string,
  "../skills/ai-agents-md/SKILL.md": askills_ai_agents_md_SKILL_md as unknown as string,
  "../skills/ai-codegraph/SKILL.md": askills_ai_codegraph_SKILL_md as unknown as string,
  "../skills/ai-research/SKILL.md": askills_ai_research_SKILL_md as unknown as string,
  "../skills/ai-adversarial-loop/SKILL.md": askills_ai_adversarial_loop_SKILL_md as unknown as string,
  "../skills/ai-writing-behavior/references/agent-behavior-specification.md": askills_ai_writing_behavior_references_agent_behavior_specification_md as unknown as string,
  "../skills/ai-writing-behavior/references/calibrating-with-trajectories.md": askills_ai_writing_behavior_references_calibrating_with_trajectories_md as unknown as string,
  "../skills/ai-writing-behavior/references/deciding-what-to-save.md": askills_ai_writing_behavior_references_deciding_what_to_save_md as unknown as string,
  "../skills/ai-writing-behavior/SKILL.md": askills_ai_writing_behavior_SKILL_md as unknown as string,
  "../skills/ai-pr-loop-fix/SKILL.md": askills_ai_pr_loop_fix_SKILL_md as unknown as string,
  "../skills/ai-explore/SKILL.md": askills_ai_explore_SKILL_md as unknown as string,
  "../skills/ai-issue-report/SKILL.md": askills_ai_issue_report_SKILL_md as unknown as string,
  "../skills/ai-orchestrator/SKILL.md": askills_ai_orchestrator_SKILL_md as unknown as string,
  "../skills/ai-debug/SKILL.md": askills_ai_debug_SKILL_md as unknown as string,
  "../skills/ai-design-md-planner/references/cli.md": askills_ai_design_md_planner_references_cli_md as unknown as string,
  "../skills/ai-design-md-planner/references/anti-slop.md": askills_ai_design_md_planner_references_anti_slop_md as unknown as string,
  "../skills/ai-design-md-planner/references/color-craft.md": askills_ai_design_md_planner_references_color_craft_md as unknown as string,
  "../skills/ai-design-md-planner/references/designmd-spec.md": askills_ai_design_md_planner_references_designmd_spec_md as unknown as string,
  "../skills/ai-design-md-planner/references/typography.md": askills_ai_design_md_planner_references_typography_md as unknown as string,
  "../skills/ai-design-md-planner/references/style-directions.md": askills_ai_design_md_planner_references_style_directions_md as unknown as string,
  "../skills/ai-design-md-planner/SKILL.md": askills_ai_design_md_planner_SKILL_md as unknown as string,
  "../skills/ai-design-md-planner/assets/DESIGN.example.md": askills_ai_design_md_planner_assets_DESIGN_example_md as unknown as string,
  "../skills/ai-design-md-planner/assets/DESIGN.template.md": askills_ai_design_md_planner_assets_DESIGN_template_md as unknown as string,
  "../skills/ai-visual-recap/references/connection.md": askills_ai_visual_recap_references_connection_md as unknown as string,
  "../skills/ai-visual-recap/references/local-files.md": askills_ai_visual_recap_references_local_files_md as unknown as string,
  "../skills/ai-visual-recap/references/wireframe.md": askills_ai_visual_recap_references_wireframe_md as unknown as string,
  "../skills/ai-visual-recap/SKILL.md": askills_ai_visual_recap_SKILL_md as unknown as string,
  "../skills/ai-visual-recap/assets/highlight.mjs": askills_ai_visual_recap_assets_highlight_mjs as unknown as string,
  "../skills/ai-test-planner/SKILL.md": askills_ai_test_planner_SKILL_md as unknown as string,
  "../skills/ai-write/references/security-md-writer.md": askills_ai_write_references_security_md_writer_md as unknown as string,
  "../skills/ai-write/references/voice.md": askills_ai_write_references_voice_md as unknown as string,
  "../skills/ai-write/references/readme-writer.md": askills_ai_write_references_readme_writer_md as unknown as string,
  "../skills/ai-write/references/contributing-writer.md": askills_ai_write_references_contributing_writer_md as unknown as string,
  "../skills/ai-write/references/documentation-writer.md": askills_ai_write_references_documentation_writer_md as unknown as string,
  "../skills/ai-write/SKILL.md": askills_ai_write_SKILL_md as unknown as string,
  "../skills/ai-config-to-project/SKILL.md": askills_ai_config_to_project_SKILL_md as unknown as string,
  "../skills/ai-code-review/SKILL.md": askills_ai_code_review_SKILL_md as unknown as string,
  "../skills/ai-review-ui/capture.cjs": askills_ai_review_ui_capture_cjs as unknown as string,
  "../skills/ai-review-ui/SKILL.md": askills_ai_review_ui_SKILL_md as unknown as string,
  "../skills/ai-note/SKILL.md": askills_ai_note_SKILL_md as unknown as string,
  "../skills/ai-read-docs/SKILL.md": askills_ai_read_docs_SKILL_md as unknown as string,
  "../skills/.chain-bundle/ai-eng-chain.ts": askills__chain_bundle_ai_eng_chain_ts as unknown as string,
  "../skills/ai-prototype/SKILL.md": askills_ai_prototype_SKILL_md as unknown as string,
  "../skills/ai-stress-test/references/tool-selection.md": askills_ai_stress_test_references_tool_selection_md as unknown as string,
  "../skills/ai-stress-test/references/safety.md": askills_ai_stress_test_references_safety_md as unknown as string,
  "../skills/ai-stress-test/SKILL.md": askills_ai_stress_test_SKILL_md as unknown as string,
  "../skills/ai-audit-code/SKILL.md": askills_ai_audit_code_SKILL_md as unknown as string,
  "../skills/ai-audit-docs/SKILL.md": askills_ai_audit_docs_SKILL_md as unknown as string,
  "../skills/ai-audit-design/references/fixes.md": askills_ai_audit_design_references_fixes_md as unknown as string,
  "../skills/ai-audit-design/references/reading.md": askills_ai_audit_design_references_reading_md as unknown as string,
  "../skills/ai-audit-design/references/accessibility-checklist.md": askills_ai_audit_design_references_accessibility_checklist_md as unknown as string,
  "../skills/ai-audit-design/agents/openai.yaml": askills_ai_audit_design_agents_openai_yaml as unknown as string,
  "../skills/ai-audit-design/scripts/audit.mjs": askills_ai_audit_design_scripts_audit_mjs as unknown as string,
  "../skills/ai-audit-design/SKILL.md": askills_ai_audit_design_SKILL_md as unknown as string,
  "../agents/ui-visual-reviewer.md": aagents_ui_visual_reviewer_md as unknown as string,
  "../agents/adversarial-reviewer.md": aagents_adversarial_reviewer_md as unknown as string,
  "../agents/ui-behavior-reviewer.md": aagents_ui_behavior_reviewer_md as unknown as string,
  "../agents/checkpoint-planner.md": aagents_checkpoint_planner_md as unknown as string,
  "../agents/fixer.md": aagents_fixer_md as unknown as string,
  "../templates/FILEMAP.md.tpl": atemplates_FILEMAP_md_tpl as unknown as string,
  "../templates/CHANGELOG.md.tpl": atemplates_CHANGELOG_md_tpl as unknown as string,
  "../templates/settings.copilot.json.tpl": atemplates_settings_copilot_json_tpl as unknown as string,
  "../templates/settings.codex.json.tpl": atemplates_settings_codex_json_tpl as unknown as string,
  "../templates/overrides.toml.tpl": atemplates_overrides_toml_tpl as unknown as string,
  "../templates/plan.html.tpl": atemplates_plan_html_tpl as unknown as string,
  "../templates/LEARNINGS.md.tpl": atemplates_LEARNINGS_md_tpl as unknown as string,
  "../templates/config.toml.tpl": atemplates_config_toml_tpl as unknown as string,
  "../templates/git-pre-push.tpl": atemplates_git_pre_push_tpl as unknown as string,
  "../templates/plugin.opencode.ts.tpl": atemplates_plugin_opencode_ts_tpl as unknown as string,
  "../templates/brainstorm.html.tpl": atemplates_brainstorm_html_tpl as unknown as string,
  "../templates/settings.copilot.cli.json.tpl": atemplates_settings_copilot_cli_json_tpl as unknown as string,
  "../templates/AGENTS.md.tpl": atemplates_AGENTS_md_tpl as unknown as string,
  "../templates/gitignore.tpl": atemplates_gitignore_tpl as unknown as string,
  "../templates/git-commit-msg.tpl": atemplates_git_commit_msg_tpl as unknown as string,
  "../templates/git-pre-commit.tpl": atemplates_git_pre_commit_tpl as unknown as string,
  "../templates/PRD.html.tpl": atemplates_PRD_html_tpl as unknown as string,
  "../templates/spec.html.tpl": atemplates_spec_html_tpl as unknown as string,
  "../templates/plugin.omp.ts.tpl": atemplates_plugin_omp_ts_tpl as unknown as string,
  "../templates/plugin.pi.ts.tpl": atemplates_plugin_pi_ts_tpl as unknown as string,
  "../templates/settings.claude.json.tpl": atemplates_settings_claude_json_tpl as unknown as string,
  "../templates/ci.yml.tpl": atemplates_ci_yml_tpl as unknown as string,
  "../templates/DECISIONS.md.tpl": atemplates_DECISIONS_md_tpl as unknown as string,
  "../templates/settings.cursor.json.tpl": atemplates_settings_cursor_json_tpl as unknown as string,
  "../templates/PERMISSIONS.md.tpl": atemplates_PERMISSIONS_md_tpl as unknown as string,
  "../templates/recap.html.tpl": atemplates_recap_html_tpl as unknown as string,
  "../templates/arch.rules.json.tpl": atemplates_arch_rules_json_tpl as unknown as string,
  "../templates/viewer.html.tpl": atemplates_viewer_html_tpl as unknown as string,
  "../scripts/checkpoint-gate.py": ascripts_checkpoint_gate_py as unknown as string,
};
