#!/usr/bin/env bash
# Prepare a throwaway browser-verification harness inside <repo>/.feature-verify/.
#
# Idempotent: safe to re-run. Installs the lightweight chrome-headless-shell
# binary (not full Chrome/Canary) and puppeteer-core only when missing, detects
# the project's dev-server command and port, writes the harness module the specs
# import, and reports whether a server is already answering on that port.
#
# It does NOT start the dev server -- backgrounding a long-lived process from
# here orphans it. Start it yourself as a background command and kill it during
# cleanup; the script prints the exact command.
#
# Nothing outside .feature-verify/ is modified except a single .gitignore line
# (only when git tracks the repo and the entry is absent).
#
# Usage: bash setup_harness.sh <repo> [--port N] [--cmd "npm run dev"]

set -euo pipefail

REPO="${1:-.}"; shift || true
FORCE_PORT=""; FORCE_CMD=""
while [ $# -gt 0 ]; do
  case "$1" in
    --port)     FORCE_PORT="$2"; shift 2 ;;
    --cmd)      FORCE_CMD="$2";  shift 2 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

cd "$REPO"
REPO_ABS="$(pwd)"
RUN_DIR="$REPO_ABS/.feature-verify"

[ -f package.json ] || { echo "ERROR: no package.json in $REPO_ABS -- is this the project root?" >&2; exit 1; }

# --- package manager ---------------------------------------------------------
if   [ -f pnpm-lock.yaml ];               then PM=pnpm; ADD="pnpm add -D";     DLX="pnpm dlx"
elif [ -f yarn.lock ];                    then PM=yarn; ADD="yarn add -D";     DLX="yarn dlx"
elif [ -f bun.lockb ] || [ -f bun.lock ]; then PM=bun;  ADD="bun add -d";      DLX="bunx"
else                                           PM=npm;  ADD="npm install -D";  DLX="npx -y"
fi

# --- dev command + port ------------------------------------------------------
DETECTED="$(node -e '
const fs=require("fs");
const pkg=JSON.parse(fs.readFileSync("package.json","utf8"));
const s=pkg.scripts||{}, d={...(pkg.dependencies||{}),...(pkg.devDependencies||{})};
const script = s.dev ? "dev" : (s.start ? "start" : (s.serve ? "serve" : ""));
const raw = script ? s[script] : "";
let port = "";
const m = raw.match(/(?:-p|--port)[= ](\d+)/); if (m) port = m[1];
if (!port) {
  if (d.next) port="3000";
  else if (d.vite || d["@sveltejs/kit"] || d.astro) port="5173";
  else if (d["react-scripts"]) port="3000";
  else if (d["@remix-run/dev"]) port="3000";
  else if (d.nuxt || d.nuxt3) port="3000";
  else port="3000";
}
process.stdout.write(JSON.stringify({script, raw, port}));
')"
DEV_SCRIPT="$(node -e "process.stdout.write(JSON.parse(process.argv[1]).script)" "$DETECTED")"
PORT="$(node -e "process.stdout.write(JSON.parse(process.argv[1]).port)" "$DETECTED")"
[ -n "$FORCE_PORT" ] && PORT="$FORCE_PORT"

if [ -n "$FORCE_CMD" ]; then
  DEV_CMD="$FORCE_CMD"
elif [ -n "$DEV_SCRIPT" ]; then
  case "$PM" in
    npm|pnpm|bun) DEV_CMD="$PM run $DEV_SCRIPT" ;;
    yarn)         DEV_CMD="yarn $DEV_SCRIPT" ;;
  esac
else
  echo "WARNING: no dev/start/serve script found. Pass --cmd \"<command>\" or start the server yourself." >&2
  DEV_CMD=""
fi

BASE_URL="http://localhost:$PORT"

# --- chrome-headless-shell ----------------------------------------------------
# The lightweight headless binary. Verified ~3.7x faster than full Chrome on a
# real page and ~9x on a local one, with byte-identical output. The install is a
# no-op when the version is already cached; either way it prints the path.
echo "Resolving chrome-headless-shell..."
CHS_OUT="$($DLX @puppeteer/browsers install chrome-headless-shell@stable --path "$HOME/.cache/puppeteer" 2>&1 | tail -1)"
CHS_PATH="${CHS_OUT#* }"
if [ ! -x "$CHS_PATH" ]; then
  echo "ERROR: could not resolve chrome-headless-shell. Installer said:" >&2
  echo "$CHS_OUT" >&2
  exit 1
fi
echo "chrome-headless-shell: $CHS_PATH"

# --- puppeteer-core (only needed for 2+ shots / waits / interaction) ----------
if [ ! -d node_modules/puppeteer-core ]; then
  echo "Installing puppeteer-core (not present)..."
  $ADD puppeteer-core >/dev/null 2>&1 || $ADD puppeteer-core
else
  echo "puppeteer-core already installed."
fi

# --- run directory ------------------------------------------------------------
mkdir -p "$RUN_DIR/specs" "$RUN_DIR/artifacts"

node -e '
const fs=require("fs");
fs.writeFileSync(process.argv[1], JSON.stringify({
  baseURL: process.argv[2],
  chromeHeadlessShell: process.argv[3],
  artifacts: process.argv[4],
  devCommand: process.argv[5],
}, null, 2) + "\n");
' "$RUN_DIR/config.json" "$BASE_URL" "$CHS_PATH" "$RUN_DIR/artifacts" "$DEV_CMD"

cat > "$RUN_DIR/harness.mjs" <<'HARNESS_EOF'
// Generated by feature-verify. Throwaway harness -- safe to delete this whole
// directory. Regenerate with scripts/setup_harness.sh.
//
// Runner is node:test (built in, nothing to install). Browser is
// chrome-headless-shell driven by puppeteer-core, launched ONCE per spec file
// and reused across every page and screenshot -- relaunching per shot costs
// ~1.1s versus ~0.19s reused, and the reuse is where the win is.
import { test, after } from 'node:test';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const config = JSON.parse(fs.readFileSync(path.join(HERE, 'config.json'), 'utf8'));
export const BASE_URL = config.baseURL;
export const ARTIFACTS = config.artifacts;
export const CHROME_HEADLESS_SHELL = config.chromeHeadlessShell;

// puppeteer-core is resolved from the repo's node_modules, not this directory.
const puppeteer = createRequire(path.join(HERE, '..', 'package.json'))('puppeteer-core');

const DEFAULT_TIMEOUT = 10_000;

let browserPromise = null;
export function browser() {
  browserPromise ??= puppeteer.launch({
    executablePath: CHROME_HEADLESS_SHELL,
    headless: 'shell', // required: the shell binary rejects Chrome's --headless=new
    args: ['--disable-gpu', '--hide-scrollbars', '--no-sandbox'],
  });
  return browserPromise;
}

after(async () => {
  if (browserPromise) await (await browserPromise).close();
});

/** One acceptance criterion per check(). The name is what lands in the report. */
export function check(name, fn, { viewport = { width: 1280, height: 720 } } = {}) {
  test(name, async (t) => {
    const page = await (await browser()).newPage();
    await page.setViewport({ ...viewport, deviceScaleFactor: 1 });

    // Diagnostics, not a gate. An uncaught exception usually names the real
    // cause outright -- read these before writing a finding's "Likely cause".
    const problems = [];
    page.on('pageerror', (e) => problems.push(`[pageerror] ${e.message}`));
    page.on('console', (m) => { if (m.type() === 'error') problems.push(`[console] ${m.text()}`); });
    page.on('response', (r) => { if (r.status() >= 500) problems.push(`[http ${r.status()}] ${r.url()}`); });

    page.setDefaultTimeout(DEFAULT_TIMEOUT);
    const origGoto = page.goto.bind(page);
    page.goto = (url, opts) => origGoto(new URL(url, BASE_URL).href, opts);

    try {
      await fn(page, t);
    } catch (err) {
      const slug = name.replace(/[^a-z0-9]+/gi, '-').toLowerCase().slice(0, 60);
      fs.mkdirSync(ARTIFACTS, { recursive: true });
      await page.screenshot({ path: path.join(ARTIFACTS, `${slug}.png`), fullPage: true }).catch(() => {});
      fs.writeFileSync(path.join(ARTIFACTS, `${slug}.html`), await page.content().catch(() => ''));
      if (problems.length) fs.writeFileSync(path.join(ARTIFACTS, `${slug}.errors.txt`), problems.join('\n'));
      err.message += `\n  evidence: ${path.join(ARTIFACTS, slug)}.{png,html}`;
      if (problems.length) err.message += `\n  browser errors:\n    ${problems.join('\n    ')}`;
      throw err;
    } finally {
      await page.close();
    }
  });
}

/** Poll until fn() is truthy. Every assertion below waits -- no fixed sleeps. */
export async function poll(fn, { timeout = DEFAULT_TIMEOUT, message = 'condition' } = {}) {
  const deadline = Date.now() + timeout;
  let last;
  for (;;) {
    try { last = await fn(); if (last) return last; } catch (e) { last = e.message; }
    if (Date.now() > deadline) throw new Error(`timed out after ${timeout}ms waiting for ${message} (last: ${last})`);
    await new Promise((r) => setTimeout(r, 100));
  }
}

const shown = async (page, sel) => {
  const el = await page.$(sel);
  if (!el) return false;
  const box = await el.boundingBox();
  return !!box && box.width > 0 && box.height > 0;
};

/** Waits for the element to exist and have a non-zero box. */
export const visible = (page, sel, o) =>
  poll(() => shown(page, sel), { ...o, message: `${sel} to be visible` });

/** Waits for the element to be gone or hidden. Assert the negative too. */
export const hidden = (page, sel, o) =>
  poll(async () => !(await shown(page, sel)), { ...o, message: `${sel} to be hidden` });

export const count = (page, sel, n, o) =>
  poll(async () => (await page.$$(sel)).length === n, { ...o, message: `${sel} to match ${n} element(s)` });

/** matcher: string (substring) or RegExp. */
export const text = (page, sel, matcher, o) =>
  poll(async () => {
    const el = await page.$(sel);
    if (!el) return false;
    const t = await el.evaluate((n) => n.innerText ?? n.textContent ?? '');
    return matcher instanceof RegExp ? matcher.test(t) : t.includes(matcher);
  }, { ...o, message: `${sel} text to match ${matcher}` });

export const value = (page, sel, expected, o) =>
  poll(async () => {
    const el = await page.$(sel);
    return !!el && (await el.evaluate((n) => n.value)) === expected;
  }, { ...o, message: `${sel} value to be ${JSON.stringify(expected)}` });

export const url = (page, matcher, o) =>
  poll(() => (matcher instanceof RegExp ? matcher.test(page.url()) : page.url().includes(matcher)),
    { ...o, message: `URL to match ${matcher}` });

/**
 * Named screenshot into artifacts/. deviceScaleFactor 1 for agent verification
 * shots; 3 only for deliverables a human will look at. On a tall full-page
 * capture dSF is wasted -- output is capped at 2000px on the long edge either
 * way, so legibility scale = 2000 / page_height_css (11px text needs the page
 * under ~3100px tall). Past ~3000px, shoot viewport-sized sections instead.
 */
export async function shot(page, name, { fullPage = false, deviceScaleFactor = 1 } = {}) {
  fs.mkdirSync(ARTIFACTS, { recursive: true });
  const file = path.join(ARTIFACTS, `${name}.png`);
  if (deviceScaleFactor !== 1) {
    const vp = page.viewport();
    await page.setViewport({ ...vp, deviceScaleFactor });
  }
  await page.screenshot({ path: file, fullPage });
  return file;
}
HARNESS_EOF

# --- dev server (probe only) ---------------------------------------------------
if curl -sS -o /dev/null --max-time 2 "$BASE_URL" 2>/dev/null; then
  SERVER_NOTE="ALREADY RUNNING on $PORT -- reused; confirm it has picked up your change"
elif [ -n "$DEV_CMD" ]; then
  SERVER_NOTE="NOT RUNNING -- start it in the background: $DEV_CMD"
else
  SERVER_NOTE="NOT RUNNING and no dev command detected -- pass --cmd or start one yourself"
fi

# --- gitignore ----------------------------------------------------------------
GITIGNORE_NOTE="not modified"
if [ -d .git ] || git rev-parse --git-dir >/dev/null 2>&1; then
  if [ -f .gitignore ] && grep -qE '^\.feature-verify/?$' .gitignore; then
    GITIGNORE_NOTE="already contained .feature-verify/"
  else
    printf '\n# throwaway feature-verify harness\n.feature-verify/\n' >> .gitignore
    GITIGNORE_NOTE="APPENDED .feature-verify/ (tell the user)"
  fi
fi

cat <<EOF

Harness ready.
  run dir     : $RUN_DIR
  specs go in : $RUN_DIR/specs/*.test.mjs   (import from '../harness.mjs')
  config      : $RUN_DIR/config.json
  browser     : $CHS_PATH
  base URL    : $BASE_URL
  dev server  : $SERVER_NOTE
  package mgr : $PM
  .gitignore  : $GITIGNORE_NOTE

Run with (pass the files, not the directory -- node --test skips dot-directories):
  cd "$REPO_ABS" && node --test .feature-verify/specs/*.test.mjs

One-off screenshot, no node needed (~0.85s):
  "$CHS_PATH" --headless --disable-gpu --hide-scrollbars \\
    --screenshot=shot.png --window-size=1280,720 --force-device-scale-factor=1 "$BASE_URL"
EOF
